---
title: "Field data work"
author: "AJ Perez-Luque (@ajpelu)"
date: "2017"
output:  
  md_document:
    toc: true
    variant: markdown_github
bibliography: references.bib
csl: ecology.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Muestreo
## Spatial Coverage 

Dos localidades de muestreo en Sierra Nevada: Robledal de Cañar y Robledal de San Juan. En cada una de las zonas dos zonas (high and low elevation). $TODO$ :red_circle: `INCLUIR LINK A MAPA CON ZONZAS Y TABLA CON NOMBRES DE MUESTREO`

## Metodologia muestreo

* Número de árboles: En Cáñar muestreamos 30 árboles (15 y 15) mientras que en San Juan 20 (10 y 10) árboles
* De cada árbol se midió la altura y el perímetro a la altura del pecho (para sacar dbh)
* Los árboles fueron seleccionados de forma aleatoria
* Tomamos al menos 2 cores perpendiculares por árbol a una altura de 1.3 m. Para ello utilizamos una barrena de Pressler
* Los cores se etiquetaron y se guardaron en pajitas hasta su manipulacion en la laboratorio

## Temporal coverage 
* 13-14 Noviembre 2016

## Collectors 
* Guillermo Gea-Izquierdo 
* Regino Zamora-Rodríguez
* Antonio J. Pérez-Luque
* Francisco J. Bonet-García (13 Nov) 

# Laboratorio: 

* Cada core se montó sobre soportes de madera convenientemente etiquetados
* Cada core se pegó utilizando cola soluble al agua y fixo (scott) 
* Ojo con montar bien las muestras (plano transversal, ver @Fritts1976)
* Una vez montadas, son lijadas (empezando por lija gruesa hasta lija menos gruesa)

## Medición: 

* Primero datación visual cruzada (sincronización // cross-dating)
* La medición de anillos se realizó utilizando un estereomicroscópio acoplado a un dispositivo LINTAB (Rinntech, Heidelberg, Germany) con una precision de 0.01 mm; y utilizando el software [TSAP-Win](http://www.rinntech.de/content/view/17/48/lang,english/index.html)
* La sincronización se realizó primero de forma visual y luego se verificó utilizando los valores de los estadísticos: 
    * Gleichläufigkeit (Glk)
    * t-value 
    * Cross-datin index (CDI)
* Posteriormente la sincronización (cross-dating) fue evaluada utilizando COFECHA [@Holmes1983] 


## References 