---
title: "ms_0_intro"
output:  
  md_document:
    toc: true
    variant: markdown_github
bibliography: ../references.bib
csl: ../ecology.csl
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Intro 

* The vegetation response to water deficit was assessed using remote sensing information and dendrocronologial data. 


### Sequías 

Although summer drought is a characteristic feature of the Mediterranean climate [@Lionello2012], an increase in the frequency and severity of drought events have been recorded for the Mediterranean region [@Hoerling2011], particularly for southern Europe [@VicenteSerrano2014; @Spinoni2015; @Stagge2017] where a trend towards drier summers has been reported for the last three decades [@Spinoni2017b]. Además las proyecciones apuntan a que este incremento en la frecuencia continuará [@Spinoni2017a]. 

In the Iberian Peninsula, major drought episodies were recorded in 1981, 1995, 2000 and 2005 [@VicenteSerrano2014]. The 2004/2005 and 2011/2012 hydrological years are considered two of the worst drought periods recorded in the Iberian Peninsula, particularly in the southern sector [@GarciaHerrera2007; @Gouveia2015; @Trigo2013]. These events were extreme in both its magnitude and spatial extent [@Gouveia2014].


> notas sequia
> 
> * the drought events have been longest and most severe in the period 1991-2010 for mediterranean are of Southern Europe  
> * Seasonally, drought frequency is projected to increase everywhere in Europe for both scenarios in spring and summer, especially over southern Europe, and less intensely in autumn [@Spinoni2017a]
> Aumento de la frecuencia de sequías en spring and summer desde 1950 hasta 2014 [@Spinoni2017b]
> Both for frequency and severity, the evolution towards drier conditions is more relevant in the last three decades over Mediterranean area in summer, 
> an increase in the drought severity in the Iberian Peninsula has been observed in the last decades [@VicenteSerrano2014]. 






Althought several works have reported these two years as some of the worst drought events, we characterised the drought at several spatio-temporal scales in the study area. From a long-term perspective, we compare the accumulated monthly precipitation at a meteorological station (Granada, Base Aérea) during the hydrological years 2004-2005 and 2011-2012 with the average of accumulated monthly precipitation for the period 1950-2015.



### Extreme sequias y ecologia 

* ojo hablar de que la sequía es un proceso natural, pero que se está viendo aumentado en los últimos años: 

Drought is a natural phenomenon that occurs when water availability is significantly below normal levels over a long period and the supply cannot meet the existing demand. 

> ver intro Ecosphere:
> Drought affects ecological systems across every climatic zone worldwide and is exacerbated by climate change and increasing anthropogenic water demands (Mishra and Singh 2010). Characterized by below-normal precipitation (Dai 2011), meteorological drought results from complex interactions between the atmosphere and hydrologic processes within the biosphere. Unlike aridity, which is a permanent feature of climate (Wilhite 1992), drought is a temporary extreme event (Palmer 1965, Mishra and Singh 2010) that can persist for extended time periods (months to years; Mishra and Singh 2010). Drought can cause significant changes in ecosystem productivity and water dynamics, and it is one of the most economically and ecologically disruptive extreme events affecting millions of people globally (Dai 2011).



Extreme climate events (e.g. droughts) severely affect forests and grasslands throuhg changes in plant physiology, phenology and carbon allocation [@Ummenhofer2017] (incluir citas para los efectos de la sequía sobre la vegetación). 

No solo efectos aislados, sino también en conjunción con otros factores, sobre todo en el mediterráneo donde convergen muchos de los factores que pueden interaccionar: 

* La sequía es un factor crucial a tener en cuenta, ya que es además de los efectos que puede tener de forma aislada, se ha visto que además presenta muchas interacciones con otros factores, siendo por tanto un factor crucial (`$IMPROVE$` ver [@DoblasMiranda2017]):
* Some interactions alter the effects of a single factor, as drought enhances or decreases the effects of atmospheric components on plant ecophysiology
* Drought and land use changes, among others, alter water resources and lead to land degradation, vegetation regeneration decline, and expansion of forest diseases.
* Climate change, and especially drought, emerges as a crucial factor in most of the reviewed interactions and therefore it should be considered when it comes to designing and applying international management policies
* Drought should be considered when designing and applying management policies.


Además la sequía se espera que tengan ...Droughts are most likely to have the largest and most long-lasting impacts globally due to large indirect and lagged impacts and long recovery especially for forest ecosystems (ver  18 en @Ummenhofer2017). Así por ejemplo se ha visto que todos los biomas presentan una vulnerabilidad similar ...
En una revision sobre la vulnerabilidad del sistema de trasnporte en plantas al embolismo inducido por sequía, ha mostrado que una convergencia de la vulnerabilidad de los bosques a la sequía, mostrando que todos los biomas son igualmente vulnerables a los fallos hidráulicos independientemente del régimen de precipitación (Choat et al. 2012, doi:10.1038/nature11688)

-- Existen evidencias que sugieren que muchos bosques son vulnerables a eventos climáticos extremos ... (Zhang) y esto puede ser especialmente relevante para especies situadas en el rear edge (completar)

Una vez dicho esto... 

* Como la dendro ayuda a evaluar las sequías (ver Gazol 2017) 
* Remote sensing: 

    * Uso de Remote sensing para estudiar la sequía --> Leer @Zhang2013 y escribir algo. Drought monitoring using remote-sensing approach was originally applied to agriculture. Several remote-sensing derived indices have been used to study the drought effects on vegetation ...
    * Leer también a @AghaKouchak2015



Climate change projections indicate that extreme events will become more common in the future (IPCC 2013), making it important that we understand how ecosystems respond to these events and the potential feedbacks to radiative forcing. 


### 
Uso de NDVI como estimador de la NPP: 

* The NDVI properties have allowed the use of this information for estimating the Net Primary Production (NPP) (Goward and Dye, 1987; Running et al., 2004; Hasenauer et al., 2012). Different studies have already found a strong relationship between NPP and radial growth (e.g., Granier et al., 2008; Babst et al., 2013, 2014a, 2014b; Vicente-Serrano et al., 2015), albeit with significant differences, particularly those related to species, sites and environmental conditions.

* Ver Gilaber et al. 2017 http://www.mdpi.com/2072-4292/9/3/193



`$NOTA$`: NDVI sirve para estimar la producción primaria neta. Existen diferentes estudio que han evaluado el efecto de la sequía sobre la producción primaria neta utilizando NDVI. 


 


### Aims
`$IMPROVE$`

In this study we combined remote sensing information and dendroecological methods to evaluate the drought impacts in both greenees and growth of *Q. pyrenaica* forests in Sierra Nevada. Specifically, 

The aims of this work were: 

* To quantify how two extreme drought events influenced the greenness and radial growth of *Q. pyreancia* forests in their rear edge,

* to analyze the resilience of these forests to successive extreme drought events,

* and to explore differences in the resilience metrics between populations located in contrasting slopes within the rear edge of the distribution of this species. 



Do northern and southern populations of Pyrenean oak forests differ in their resistance, resilience or recovery to extreme drought events? 
 




## References 
