---
title: "discussion"
author: "AJ Perez-Luque (@ajpelu); G. Gea-Izquierdo"
date: "2017"
output:  
  md_document:
    toc: true
    variant: markdown_github
bibliography: ../refs/references.bib
csl: ../refs/ecology.csl
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Discussions notes  

## Greenness 

* Aproximadamete el x% de los robledales mostraron un incremento en los valores de productividad (greenees) ... (relacionar con tendencias EVI y ontologias).
* tendencias ontologias 

* Si analizamos el plot de trajectorias (evi medio anual), vemos como en 2005 y 2012 se observó un browning para los valores medios de EVI. En ambos casos, se observó un patrón homogéneo de browing, aunque en 2012 el browning fue mucho menor. 


## Dos cronos en Cañar 
* @GeaIzquierdo2014 muestrea solo en CA-Low (QUPY10) y obtiene resultados similares a CA-Low. 
* En tan poco espacio hay diferencias enormes entre las dos cronos
* *Las tendencias de BAI de Cáñar baja altitud son diferentes a las del norte, las cuales se parecen mucho a las que suelen encontrarse en la mayoría de sitios. Puedes mirar por ejemplo las tendencias de las líneas negras (de más de 100 años, sobre todo) en la Fig 2 del artículo de Ecosystems… fíjate que QUPY3 se parece más a QUPY10… y QUPY3 era la única dehesa (en parte) y uno de los sitios más secos (por otro lado, aunque frío). En fin, todo esto es algo especulativo, pero sirva como exploración de tus cronos, y para mostrar que me parece muy interesante la diferencia entre Cáñar alto y bajo (y nuevo).* 

## Reducción crecimiento y sequías 

Se observó una gran reducción de crecimiento en 1994-1995, 1999 y 2005 para Pinus nigra en el SE de Andalusia [@SanchezSalguero2013] coincidiendo con años de sequía para esa zona. La máxima reducción en crecimiento fue observada para 2005, siendo significativamente mayor que para el resto de años [@SanchezSalguero2013].


## Dendro

### Diferencias crecimiento entre sitios. 
Mayor crecimiento en los robles situados en CaHigh. Sorprende que en el rear edge de la distribución de la especie, en la cara sur dentro de este rear edge, y en la parte mas alta (estas parcelas están en el treeline de la especie en SN) es donde encontramos mayores crecimientos. Parece que los robles estuvieran mejor en esta zona. Algunas reflexiones

* Quizá están creciendo donde les están dejando (menor impacto antrópico)
* ¿Menor estrés hídrico en zonas mas altas? 
* ¿Diferencias entre suelos? (ver artículo [@CoboDiaz2017] que compara suelos de Cáñar). En este estudio sobre microbiota del suelo, analizó tres sitios: por encima del treline (XZF), low altitudinal oak forest (LAF) and high altitudinal oak forest (HAF). LAF está mucho mas bajo, pero HAF está cerca de las parcelas caHigh y encontró lo siguiente: 

  * tipo de suelo: LAF es Sandy-loam, HAF es loam
  * HAF tuvo los valores mayores de disponibilidad hídrica (% available water tabla s1 en [@CoboDiaz2017]) 
  * Los tres sitios eran pobres en materia orgánica, pero el HAF dobló los valores de los otros dos sitios
  * No diferencias en contenido de N, C/N ratio similares en HAF, y LAF


Sorprende que en Cáñar haya diferencias tan grandes de crecimiento estándo tan cerca. ¿Puede estar relacionado con intensidad de uso antrópico? De hecho la Ca-Low tiene crecimientos similares a SJ. 



## Relaciones crecimiento-clima en otras especies 


























and higher values of tree-growth (Table 2). 

El sitio caH mostró además los mayores valores de AR(1) y de MS

El sitio del norte, mostró mayores valores de MS (Table 2). ¿esto sugiere que este sitio tiene una alta limitación climática? 


Different growth trends were observed for each site (Figure 5). Ca-High (the highest elevation site) had higher values of tree growth than the other sites. 











notas para discusión 

En ambos casos (evi y bai) la sequía de 2005 y de 2012 redujeron el greenness y el crecimiento. Además en ambos casos la sequía de 2005 redujo mas la variable, sin embargo, para el greenness si existen diferencias entre ambos eventos de sequía, mientras que para el crecimiento no. Por tanto podemos decir que se ha reducido el greennes pero para el crecimiento esto está mas amortiguado. 

Al explorar la resistencia por sitio y drought se observa una curiosidad. La resistencia de los robledales de CaLow se mantiene casi igual. La de la cara norte (SJ) sufre mucho en 2005 y luego se recupera un poco. La de caH presenta menor resistencia en 2012 que en 2005 (y eso llama la atención)








## References 
