---
title: "material and methods"
author: "AJ Perez-Luque (@ajpelu); G. Gea-Izquierdo"
date: "2017"
output:  
  md_document:
    toc: true
    variant: markdown_github
bibliography: references.bib
csl: ecology.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Materials and methods 

## Tree sampling 
Samplig was carried during autumn of 2016. Trees were sampled at two locations located in contrasting slopes of Sierra Nevada: San Juan (SJ; northern site) and Cáñar (CA; southern site) (Table 1). Both sites were oak monospecific and representatives of two of the three the population's cluster identified for this specie in this mountain range (:red_circle: mejorar; citar Pérz-Luque et al..). In each site between 15 and 20 dominant trees were sampled. Two cores of 5 mm of diameter were taken per tree at 1.3 m using an increment borer. Diameter at breat height (DBH) and total height were recorded for each tree. Increment cores were air dried, glued onto wooden mounts and sanded. Annual radial growth (ring width, RW) were measured with a LINTAB measuring device (:red_circle: Rinntech 2003) coupled to a stereomicroscope, with an accuracy of 0.01 mm. Individual ring series were visually and statistically cross-dated with TSAP software (:red_circle: Frank Rinn, Heidelberg, Germany), using the statistics Gleichläufigkeit (GLK), t-value and the crossdating index (CDI). Validation of the croos-dating was done using COFECHA software [@Holmes1983]. 


## Dendrochronological methods
... dendro
For each focal tree we measured diameter at breast height (DBH) and total height. 
A total of xx trees were sampled. 
...


We built chronologies for each site (two) 



Site chronologies were built by averaging all tree BAI measurement of the same site. To explore similarity within locality, each site chronology was smoothed using centred moving averages with different window sizes, and then Pearson's correlation coefficient between the two chronologies of the same locality (higher and lower elevation) were calculated. Significance was tested using 1000 boostrap replicates and with 95 % confidence intervals built using the R packgae `boot` [@Canty2016]



## References 
