---
title: "ms_tables_portrait"
output:
  word_document:
    fig_caption: yes
    fig_height: 6
    fig_width: 7.5
    highlight: null
    reference_docx: template_tables_portrait.docx
bibliography: ../refs/references.bib
csl: ../refs/ecology.csl
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, echo=FALSE}
library(tidyverse)
library(here)
library(pander)
library(kableExtra)
library(knitr)
library(dplyr)
```

```{r, echo=FALSE}
show_text <- FALSE
```



```{r echo=FALSE, results='asis', eval=show_text}
cat("
# Lista de tablas

# Table 1 
* Site features 

# Table 2 
* Dendro summary

# Table 3 ANOVAS resilience BAI and EVI 

# Table RS1 
* Estimadores huber resiliences EVI 

# Table RS2

* Estimadores huber resiliences Bai 


")
```


## Table 1. Characteristics of the sampled plots 

```{r, echo=FALSE}
# https://rdrr.io/cran/pander/man/panderOptions.html 


topo <- read.csv(here("/data/sites_summary", "site_general.csv"), header = TRUE)
ages <- read.csv(here("/data/dendro_summary", "site3_avg_ages.csv"), header = TRUE)
dendro_summ <- read.csv(here("/data/dendro_summary", "site3_dendro_summary.csv"), header = TRUE)
biotic <- read.csv(here("/data/competence", "biotic_stand_features.csv"), header = TRUE)

t1raw <- topo %>% inner_join(ages, by='site') %>% 
  inner_join(dendro_summ, by='site') %>% 
  inner_join(biotic, by='site')

t1raw <- t1raw %>% mutate(name = case_when(
  site == 'caH' ~ 'CA-High', 
  site == 'caL' ~ 'CA-Low',
  site == 'sj' ~ 'SJ')) 



t1 <- t1raw %>% dplyr::select(
  name, lat_m, long_m, elev_mean, slope_mean, 
  n_trees, n_radii, dn_mean, dn_sd, h_mean, h_sd, age_mean, age_std, 
  dn_mean_all, dn_sd_all, h_mean_all, h_sd_all,
  ba_mean, ba_sd, stand_density_mean, stand_density_sd) %>% 
  mutate(pare = ")") %>% 
  mutate_at(c(2,3,5,18,19), round, 2) %>% 
  mutate_at(4, round, 0) %>% 
  mutate_at(c(8:17, 20:21), round, 1) %>% 
  unite(dn, c(dn_mean, dn_sd), sep=" (") %>% 
  unite(h, c(h_mean, h_sd), sep=" (") %>% 
  unite(age, c(age_mean, age_std), sep=" (") %>% 
  unite(dn_all, c(dn_mean_all, dn_sd_all), sep=" (") %>% 
  unite(h_all, c(h_mean_all, h_sd_all), sep=" (") %>% 
  unite(ba, c(ba_mean, ba_sd), sep=" (") %>% 
  unite(stand_density, c(stand_density_mean, stand_density_sd), sep=" (") %>% 
  mutate(
    dn = paste0(dn, pare),
    h = paste0(h, pare), 
    age = paste0(age, pare),
    dn_all = paste0(dn_all, pare),
    h_all = paste0(h_all, pare),
    ba = paste0(ba, pare),
    stand_density = paste0(stand_density, pare)) %>% 
  dplyr::select(-pare)


# ADD data climate
# clima obsnev (from repo clima SN; son datos de mapas pasados 100 x 100 1960 - 2010)

clima <- read.csv(here("/data/climate_obsnev", "obsnev_qp_pop.csv"), header = TRUE)
cli <- clima %>% filter(pop %in% c(2,6)) %>% mutate_if(is.numeric, funs(round(., 1))) %>% 
  dplyr::select(pop, mean, variable) %>% 
  spread(variable, mean) %>% 
  mutate(name = case_when(
    pop == 2 ~ 'SJ',
    pop == 6 ~ 'CA-High'
  )) %>% dplyr::select(-pop) 

# duplicate row for CA site
x <- cli[2,] 
x$name <- 'CA-Low'
cli <- cli %>% bind_rows(x) %>% 
  mutate_at(1, round, 0) %>% 
  unite(temp, c(tmin, tmax), sep=" - ") 




t1 <- t1 %>% inner_join(cli, by='name') %>% dplyr::select(name, lat_m, long_m, elev_mean, slope_mean, prec, temp, n_trees:stand_density)



colnames (t1) <- c("Name", "Lat (&deg;)", "Long (&deg;)", "Elevation (m)", "Slope (&deg;)", 
                   "Prec. (mm)", "Temp ((&deg; C)", 
                   "# trees", '# cores', "Dbh (cm)", "Height (m)", "Age (years)", 
                   "Dbh all (cm)", "Height all (m)", "BA (m2/ha)", "Density (trees/ha)")



pander(t1, split.table = Inf)
```


## Table 2. Dendro summary 

```{r, echo=FALSE}
t2 <- t1raw %>% dplyr::select(
  site, first_year, last_year, 
  length_year, length_year5, 
  n_trees, n_radii,
  rw_mean, rw_std, ms2, ar1, rbar.wt, eps)  %>% 
  mutate(pare = ")") %>% 
  mutate_at(c(8:13), round, 3) %>% 
  unite(length_year, c(length_year,length_year5), sep=" (") %>%
  unite(RW, c(rw_mean,rw_std), sep=" (") %>%
  mutate(
    length_year = paste0(length_year, pare),
    RW = paste0(RW, pare)) %>% 
  dplyr::select(-pare)
  
  
colnames(t2) <- c("Name", "First year", "Last year", "Length (years)",  
                   "# trees", '# cores', "RW (mm)", "MS", "AR(1)", "Rbt", "EPS") 

pander(t2,
       split.table = Inf)

```




## Table 3. Robust ANOVAS (F-value)
```{r, echo=FALSE, include = FALSE}
### Table R1_evi
df <- read.csv(here("/out/anovas_resilience/huber_evi", "trimmed_anovas.csv"), header = TRUE)
names(df) <- c('factores', 'F', 'p', 'variables')

dff <- df %>% gather(temp, numeros, F, p) %>% 
  unite(temp1, variables, temp) %>% 
  spread(temp1, numeros) %>% 
  mutate(factores = recode(factores, 
                           "disturb_year" = "Disturb", 
                           "disturb_year:site" = "Disturb X Site", 
                           "site" = "Site")) %>% 
  arrange(match(factores, c("Disturb", "Site", "Disturb X Site")))


# knitr::kable(dff, 
#       col.names = c("", "F", "p", "F", "p", "F", "p", "F", "p"),
#       digits=c(0,2,3,2,3,2,3,2,3))


colnames(dff) <- c("", "rc\nF", "rc\np", "rrs\nF", "rrs\np", "rs\nF", "rs\np", "rt\nF", "rt\np")
pander(dff,
             round=c(0,2,3,2,3,2,3,2,3),
             digits=c(0,5,4,5,4,5,4,5,4),
             keep.line.breaks = TRUE
             )
dff

```

```{r, echo=FALSE, include = FALSE}
### Table R1_evi sin rrs 
df <- read.csv(here("/out/anovas_resilience/huber_evi", "trimmed_anovas.csv"), header = TRUE)
names(df) <- c('factores', 'F', 'p', 'variables')

dff <- df %>% 
  filter(variables != "rrs") %>% 
  gather(temp, numeros, F, p) %>% 
  unite(temp1, variables, temp) %>% 
  spread(temp1, numeros) %>% 
  mutate(factores = recode(factores, 
                           "disturb_year" = "Disturb", 
                           "disturb_year:site" = "Disturb X Site", 
                           "site" = "Site")) %>% 
  arrange(match(factores, c("Disturb", "Site", "Disturb X Site")))


# knitr::kable(dff, 
#       col.names = c("", "F", "p", "F", "p", "F", "p", "F", "p"),
#       digits=c(0,2,3,2,3,2,3,2,3))

dff_evi <- dff %>% mutate(target = 'EVI')

colnames(dff) <- c("", "rc\nF", "rc\np", "rs\nF", "rs\np", "rt\nF", "rt\np")
pander(dff,
             round=c(0,2,3,2,3,2,3,2,3),
             digits=c(0,5,4,5,4,5,4,5,4),
             keep.line.breaks = TRUE
             )
dff

```

```{r, echo=FALSE, include = FALSE}

### Table R1_bai
df <- read.csv(here("/out/anovas_resilience/huber_bai", "trimmed_anovas.csv"), header = TRUE)
names(df) <- c('factores', 'F', 'p', 'variables')

dff <- df %>% gather(temp, numeros, F, p) %>% 
  unite(temp1, variables, temp) %>% 
  spread(temp1, numeros) %>% 
  mutate(factores = recode(factores, 
                           "disturb_year" = "Disturb", 
                           "disturb_year:site" = "Disturb X Site", 
                           "site" = "Site")) %>% 
  arrange(match(factores, c("Disturb", "Site", "Disturb X Site")))


# knitr::kable(dff, 
#       col.names = c("", "F", "p", "F", "p", "F", "p", "F", "p"),
#       digits=c(0,2,3,2,3,2,3,2,3))

colnames(dff) <- c("", "rc\nF", "rc\np", "rrs\nF", "rrs\np", "rs\nF", "rs\np", "rt\nF", "rt\np")
pander(dff,
             round=c(0,2,3,2,3,2,3,2,3),
             digits=c(0,5,4,5,4,5,4,5,4),
             keep.line.breaks = TRUE
             )
dff

```

```{r, echo=FALSE, include = FALSE}
### Table R1_bai sin rrs 
df <- read.csv(here("/out/anovas_resilience/huber_bai", "trimmed_anovas.csv"), header = TRUE)
names(df) <- c('factores', 'F', 'p', 'variables')

dff <- df %>% 
  filter(variables != "rrs") %>% 
  gather(temp, numeros, F, p) %>% 
  unite(temp1, variables, temp) %>% 
  spread(temp1, numeros) %>% 
  mutate(factores = recode(factores, 
                           "disturb_year" = "Disturb", 
                           "disturb_year:site" = "Disturb X Site", 
                           "site" = "Site")) %>% 
  arrange(match(factores, c("Disturb", "Site", "Disturb X Site")))

dff_bai <- dff %>% mutate(target = 'BAI')

# knitr::kable(dff, 
#       col.names = c("", "F", "p", "F", "p", "F", "p", "F", "p"),
#       digits=c(0,2,3,2,3,2,3,2,3))


colnames(dff) <- c("", "rc\nF", "rc\np", "rs\nF", "rs\np", "rt\nF", "rt\np")
pander(dff,
             round=c(0,2,3,2,3,2,3,2,3),
             digits=c(0,5,4,5,4,5,4,5,4),
             keep.line.breaks = TRUE
             )
dff

```

```{r, echo=FALSE}
# table 2 (r1)
dffs <- dff_bai %>% bind_rows(dff_evi)

# write.csv(dffs, here("/out/anovas_resilience", "trimmed_anovas_joined.csv"), row.names = FALSE)

# kable(dffs, format = "latex", booktabs = T,
#       col.names = c("", "F", "p", "F", "p", "F", "p", "variable"),
#       digits=c(0,2,3,2,3,2,3,2,3,0)) %>% 
#   kable_styling(font_size = 8) %>% 
#   add_header_above(c("", "rc" = 2, "rs" = 2, "rt" = 2))

colnames(dffs) <- c("", "rc\nF", "rc\np", "rs\nF", "rs\np", "rt\nF", "rt\np", "variable")
pander(dffs,
             round=c(0,2,3,2,3,2,3,2,3,0),
             digits=c(0,5,4,5,4,5,4,5,4,0),
             keep.line.breaks = TRUE
             )
```


## Table RS1 

* Estimadores huber resiliences EVI 

```{r, echo = FALSE, warning = FALSE}
mraw <- df <- read.csv(here("/out/anovas_resilience/huber_evi", "robust_mhuber_agg.csv"), header = TRUE)

m <- mraw %>% 
  filter(var != 'rrs') %>% 
  rename(variables = var)  %>% 
  dplyr::select(c(-n, -Letter)) %>% 
 unite("mh", c("M.Huber", "ci"), sep = "\n")


# Datos agrupados para todos los sitios 
mraw_a <- df <- read.csv(here("/out/anovas_resilience/huber_evi", "robust_mhuber_agg_a.csv"), header = TRUE)

m_a <- mraw_a %>% 
  filter(var != 'rrs') %>% 
  rename(variables = var)  %>% 
  dplyr::select(c(-n, -Letter)) %>%  
  unite("mh", c("M.Huber", "ci"), sep = "\n") %>% 
  mutate(site = "z_all") 

# Datos agrupados para todos los sitios 
mraw_b <- df <- read.csv(here("/out/anovas_resilience/huber_evi", "robust_mhuber_agg_b.csv"), header = TRUE)

m_b <- mraw_b %>% 
  filter(var != 'rrs') %>% 
  rename(variables = var)  %>% 
  dplyr::select(c(-n, -Letter)) %>%  
  unite("mh", c("M.Huber", "ci"), sep = "\n") %>%
  mutate(disturb_year = 2099) 


mm <- m %>% 
  bind_rows(m_a) %>%
  bind_rows(m_b) %>% 
  gather(temp, numeros, mh) %>% 
  unite(temp1, c(variables, disturb_year), temp) %>% 
  spread(temp1, numeros, fill = "") 

mm <- mm %>% 
  dplyr::select(site, 
                rt_2005_mh, rc_2005_mh, rs_2005_mh,
                rt_2012_mh, rc_2012_mh, rs_2012_mh,
                rt_2099_mh, rc_2099_mh, rs_2099_mh)

colnames(mm) <- c(" \nsite", "2005\nRt", "2005\nRc", "2005\nRs", "2012\nRt", "2012\nRc", "2012\nRs", "Rt", "Rc", "Rs")
pander(mm, keep.line.breaks = TRUE, split.table = Inf)
```


# Table RS2 

* Estimadores huber resiliences Bai 

```{r, echo = FALSE, warning = FALSE}
mraw <- df <- read.csv(here("/out/anovas_resilience/huber_bai", "robust_mhuber_agg.csv"), header = TRUE)

m <- mraw %>% 
  filter(var != 'rrs') %>% 
  rename(variables = var)  %>% 
  dplyr::select(c(-n, -Letter)) %>% 
 unite("mh", c("M.Huber", "ci"), sep = "\n")


# Datos agrupados para todos los sitios 
mraw_a <- df <- read.csv(here("/out/anovas_resilience/huber_bai", "robust_mhuber_agg_a.csv"), header = TRUE)

m_a <- mraw_a %>% 
  filter(var != 'rrs') %>% 
  rename(variables = var)  %>% 
  dplyr::select(c(-n, -Letter)) %>%  
  unite("mh", c("M.Huber", "ci"), sep = "\n") %>% 
  mutate(site = "z_all") 

# Datos agrupados para todos los sitios 
mraw_b <- df <- read.csv(here("/out/anovas_resilience/huber_bai", "robust_mhuber_agg_b.csv"), header = TRUE)

m_b <- mraw_b %>% 
  filter(var != 'rrs') %>% 
  rename(variables = var)  %>% 
  dplyr::select(c(-n, -Letter)) %>%  
  unite("mh", c("M.Huber", "ci"), sep = "\n") %>%
  mutate(disturb_year = 2099) 


mm <- m %>% 
  bind_rows(m_a) %>%
  bind_rows(m_b) %>% 
  gather(temp, numeros, mh) %>% 
  unite(temp1, c(variables, disturb_year), temp) %>% 
  spread(temp1, numeros, fill = "") 

mm <- mm %>% 
  dplyr::select(site, 
                rt_2005_mh, rc_2005_mh, rs_2005_mh,
                rt_2012_mh, rc_2012_mh, rs_2012_mh,
                rt_2099_mh, rc_2099_mh, rs_2099_mh)

colnames(mm) <- c(" \nsite", "2005\nRt", "2005\nRc", "2005\nRs", "2012\nRt", "2012\nRc", "2012\nRs", "Rt", "Rc", "Rs")
pander(mm, keep.line.breaks = TRUE, split.table = Inf)
```


```{r, echo = FALSE, warning = FALSE, eval = FALSE}

# Este código es para print la tabla anterior en formato pdf latex (ver state_ms)c
### OJO REVISAR 
# ------------------------------

mraw <- df <- read.csv(here("/out/anovas_resilience/huber_bai", "robust_mhuber_agg.csv"), header = TRUE)

m <- mraw %>% 
  filter(var != 'rrs') %>% 
  rename(variables = var)  %>% 
  dplyr::select(c(-n, -Letter)) 


# Datos agrupados para todos los sitios 
mraw_a <- df <- read.csv(here("/out/anovas_resilience/huber_bai", "robust_mhuber_agg_a.csv"), header = TRUE)

m_a <- mraw_a %>% 
  filter(var != 'rrs') %>% 
  rename(variables = var)  %>% 
  dplyr::select(c(-n, -Letter)) %>%  
  mutate(site = "z_all") 

# Datos agrupados para todos los sitios 
mraw_b <- df <- read.csv(here("/out/anovas_resilience/huber_bai", "robust_mhuber_agg_b.csv"), header = TRUE)

m_b <- mraw_b %>% 
  filter(var != 'rrs') %>% 
  rename(variables = var)  %>% 
  dplyr::select(c(-n, -Letter)) %>%  
  mutate(disturb_year = 2099) 


mm <- m %>% 
  bind_rows(m_a) %>%
  bind_rows(m_b) %>% 
  gather(temp, numeros, c(M.Huber, ci)) %>% 
  unite(temp1, c(variables, disturb_year), temp) %>% 
  spread(temp1, numeros, fill = "") 

mm <- mm %>% 
  dplyr::select(site, 
                rc_2005_M.Huber, rc_2005_ci, rt_2005_M.Huber, rt_2005_ci, rs_2005_M.Huber, rs_2005_ci,
                rc_2012_M.Huber, rc_2012_ci, rt_2012_M.Huber, rt_2012_ci, rs_2012_M.Huber, rs_2012_ci,
                rc_2099_M.Huber, rc_2099_ci, rt_2099_M.Huber, rt_2099_ci, rs_2099_M.Huber, rs_2099_ci)


mmt <- mm %>%
   rownames_to_column %>% 
   gather(var, value, -rowname) %>% 
   spread(rowname, value) 

colnames(mmt) <- c("var", "SJ", "caH", "caL", "z_all") 
mmt <- mmt[-19,] 
mmt <- mmt %>% 
  mutate(vars = c(rep("Rc",6), rep("Rt",6), rep("Rs",6)),
         year = c(rep(
           c(rep("2005", 2), 
             rep("2012", 2),
             rep(" ", 2)), 3))) %>% 
  dplyr::select(vars, year, SJ, caH, caL, var)


kable(mmt, 
      format = "latex", booktabs = T) %>% 
  kable_styling(font_size = 6) %>% 
  add_header_above(c("", "", "Northern", "Southern" = 2, "")) 
```




