---
title: "ms_tables"
output:  
  md_document:
    toc: true
    variant: markdown_github
bibliography: ../references.bib
csl: ../ecology.csl
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, echo=FALSE}
library(tidyverse)
library(here)
library(pander)
library(kableExtra)
library(knitr)
library(dplyr)
```

```{r, echo=FALSE}
show_text <- FALSE
```

```{r}
panderOptions('table.split.table', Inf)
```

```{r echo=FALSE, results='asis', eval=show_text}
cat("
# Lista de tablas

# Table 1 
* Site features 

# Table 2 
* Dendro summary

# Table 2 ANOVAS resilience BAI and EVI 

# Table RS1 
* Estimadores huber resiliences EVI 

# Table RS2

* Estimadores huber resiliences Bai 


")
```


## Table 1. Characteristics of the sampled plots 
```{r, echo=FALSE}
topo <- read.csv(here("/data/sites_summary", "site_general.csv"), header = TRUE)
ages <- read.csv(here("/data/dendro_summary", "site3_avg_ages.csv"), header = TRUE)
dendro_summ <- read.csv(here("/data/dendro_summary", "site3_dendro_summary.csv"), header = TRUE)
biotic <- read.csv(here("/data/competence", "biotic_stand_features.csv"), header = TRUE)

t1raw <- topo %>% inner_join(ages, by='site') %>% 
  inner_join(dendro_summ, by='site') %>% 
  inner_join(biotic, by='site')


t1raw <- t1raw %>% mutate(name = case_when(
  site == 'caH' ~ 'Cáñar-High', 
  site == 'caL' ~ 'Cáñar-Low',
  site == 'sj' ~ 'San Juan')) 

t1 <- t1raw %>% dplyr::select(
  site, lat_m, long_m, elev_mean, elev_min, elev_max, slope_mean, 
  n_trees, n_radii, dn_mean, dn_sd, h_mean, h_sd, age_mean, age_std, 
  dn_mean_all, dn_sd_all, h_mean_all, h_sd_all,
  ba_mean, ba_sd, stand_density_mean, stand_density_sd) 


colnames (t1) <- c("Name", "Lat (º)", "Long (º)", "Elevation (m)", "", "", "Slope (º)", 
                   "# trees", '# cores', "Dbh (cm)", "", "Height (m)", "", "Age (years)", "", 
                   "Dbh all (cm)", "", "Height all (m)", "", "BA (m2/ha)", "", "Density (trees/ha)", "")

pander(t1,
       round=c(0, 2, 2, 0, 0, 0, 2, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1),
             keep.line.breaks = TRUE)
```


## Table 2. Robust ANOVAS (F-value)
```{r, echo=FALSE, include = FALSE}
### Table R1_evi
df <- read.csv(here("/out/anovas_resilience/huber_evi", "trimmed_anovas.csv"), header = TRUE)
names(df) <- c('factores', 'F', 'p', 'variables')

dff <- df %>% gather(temp, numeros, F, p) %>% 
  unite(temp1, variables, temp) %>% 
  spread(temp1, numeros) %>% 
  mutate(factores = recode(factores, 
                           "disturb_year" = "Disturb", 
                           "disturb_year:site" = "Disturb X Site", 
                           "site" = "Site")) %>% 
  arrange(match(factores, c("Disturb", "Site", "Disturb X Site")))


# knitr::kable(dff, 
#       col.names = c("", "F", "p", "F", "p", "F", "p", "F", "p"),
#       digits=c(0,2,3,2,3,2,3,2,3))


colnames(dff) <- c("", "rc\nF", "rc\np", "rrs\nF", "rrs\np", "rs\nF", "rs\np", "rt\nF", "rt\np")
pander(dff,
             round=c(0,2,3,2,3,2,3,2,3),
             digits=c(0,5,4,5,4,5,4,5,4),
             keep.line.breaks = TRUE
             )
dff

```

```{r, echo=FALSE, include = FALSE}
### Table R1_evi sin rrs 
df <- read.csv(here("/out/anovas_resilience/huber_evi", "trimmed_anovas.csv"), header = TRUE)
names(df) <- c('factores', 'F', 'p', 'variables')

dff <- df %>% 
  filter(variables != "rrs") %>% 
  gather(temp, numeros, F, p) %>% 
  unite(temp1, variables, temp) %>% 
  spread(temp1, numeros) %>% 
  mutate(factores = recode(factores, 
                           "disturb_year" = "Disturb", 
                           "disturb_year:site" = "Disturb X Site", 
                           "site" = "Site")) %>% 
  arrange(match(factores, c("Disturb", "Site", "Disturb X Site")))


# knitr::kable(dff, 
#       col.names = c("", "F", "p", "F", "p", "F", "p", "F", "p"),
#       digits=c(0,2,3,2,3,2,3,2,3))

dff_evi <- dff %>% mutate(target = 'EVI')

colnames(dff) <- c("", "rc\nF", "rc\np", "rs\nF", "rs\np", "rt\nF", "rt\np")
pander(dff,
             round=c(0,2,3,2,3,2,3,2,3),
             digits=c(0,5,4,5,4,5,4,5,4),
             keep.line.breaks = TRUE
             )
dff

```

```{r, echo=FALSE, include = FALSE}

### Table R1_bai
df <- read.csv(here("/out/anovas_resilience/huber_bai", "trimmed_anovas.csv"), header = TRUE)
names(df) <- c('factores', 'F', 'p', 'variables')

dff <- df %>% gather(temp, numeros, F, p) %>% 
  unite(temp1, variables, temp) %>% 
  spread(temp1, numeros) %>% 
  mutate(factores = recode(factores, 
                           "disturb_year" = "Disturb", 
                           "disturb_year:site" = "Disturb X Site", 
                           "site" = "Site")) %>% 
  arrange(match(factores, c("Disturb", "Site", "Disturb X Site")))


# knitr::kable(dff, 
#       col.names = c("", "F", "p", "F", "p", "F", "p", "F", "p"),
#       digits=c(0,2,3,2,3,2,3,2,3))

colnames(dff) <- c("", "rc\nF", "rc\np", "rrs\nF", "rrs\np", "rs\nF", "rs\np", "rt\nF", "rt\np")
pander(dff,
             round=c(0,2,3,2,3,2,3,2,3),
             digits=c(0,5,4,5,4,5,4,5,4),
             keep.line.breaks = TRUE
             )
dff

```

```{r, echo=FALSE, include = FALSE}
### Table R1_bai sin rrs 
df <- read.csv(here("/out/anovas_resilience/huber_bai", "trimmed_anovas.csv"), header = TRUE)
names(df) <- c('factores', 'F', 'p', 'variables')

dff <- df %>% 
  filter(variables != "rrs") %>% 
  gather(temp, numeros, F, p) %>% 
  unite(temp1, variables, temp) %>% 
  spread(temp1, numeros) %>% 
  mutate(factores = recode(factores, 
                           "disturb_year" = "Disturb", 
                           "disturb_year:site" = "Disturb X Site", 
                           "site" = "Site")) %>% 
  arrange(match(factores, c("Disturb", "Site", "Disturb X Site")))

dff_bai <- dff %>% mutate(target = 'BAI')

# knitr::kable(dff, 
#       col.names = c("", "F", "p", "F", "p", "F", "p", "F", "p"),
#       digits=c(0,2,3,2,3,2,3,2,3))


colnames(dff) <- c("", "rc\nF", "rc\np", "rs\nF", "rs\np", "rt\nF", "rt\np")
pander(dff,
             round=c(0,2,3,2,3,2,3,2,3),
             digits=c(0,5,4,5,4,5,4,5,4),
             keep.line.breaks = TRUE
             )
dff

```

```{r, echo=FALSE}
# table 2 (r1)
dffs <- dff_bai %>% bind_rows(dff_evi)

# write.csv(dffs, here("/out/anovas_resilience", "trimmed_anovas_joined.csv"), row.names = FALSE)

# kable(dffs, format = "latex", booktabs = T,
#       col.names = c("", "F", "p", "F", "p", "F", "p", "variable"),
#       digits=c(0,2,3,2,3,2,3,2,3,0)) %>% 
#   kable_styling(font_size = 8) %>% 
#   add_header_above(c("", "rc" = 2, "rs" = 2, "rt" = 2))

colnames(dffs) <- c("", "rc\nF", "rc\np", "rs\nF", "rs\np", "rt\nF", "rt\np", "variable")
pander(dffs,
             round=c(0,2,3,2,3,2,3,2,3,0),
             digits=c(0,5,4,5,4,5,4,5,4,0),
             keep.line.breaks = TRUE
             )
```





