---
title: "Dendrocronology notes"
author: "AJ Perez-Luque (@ajpelu)"
date: "2016 Nov"
output:  
  md_document:
    toc: true
    variant: markdown_github
bibliography: references.bib
csl: ecology.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Ring Width measurement 

## Notes from [@GeaIzquierdo2012Tree]

* Two cores were taken at 1.30 m from each selected tree
* The stem diamenter and tree height were measured
* Cores were air dried, fixed in woodend mounts, sanded and RW measured 
* Ring-width series were visually cross-dated and the dating was checked using COFECHA `$TODO$` Check COFECHA
* Ring-width inidces were obtained by removing the age trend using 30-year individual splines and autocorrelation before computing the final indices using the ration between the observed and expected annual mean growth 




# Features of vascular system of *Q. pyrenaica* 

* Ring-porous tress are assumed to be particularly sensitive to climate warming, because they operate with narrow hydraulic safety margins (see Choat et al. )[@PerezdeLis2016] 

* Vessel size chronologies were related to previous summer rainfall (from González-González et al. 2014)[@PerezdeLis2016]

### Spring tree phenology [@PerezdeLis2016]

| Phases                                 | DOY       | Months                | Sites <sup>1</sup> | Year <sup>1</sup> |
|----------------------------------------|-----------|-----------------------|--------------------|-------------------|
| Cambial resumption (cambial divisions) | 58 - 94   | late Feb - early Apr  | ***                | -                 |
| Earlywood vessel (EV) enlargement      | 71 - 182  | mid March - early Jul | ***                | ***               |
| EV maturation                          | 100 - 162 | early April - mid Jun | ***                | ***               |
| Leaf expansion                         | 126 - 177 | early May - late June | ***                | ***               |

* <sup>1</sup>: Differences between sites and years (2012, 2013)

* Budburst dates were highly correlated to those of wood formation particularly to the onset of EV maturation
* Full leaf expansion and the end of EV enlargement were simultaneous. EV formation and leaf unfoulding showed to be coupled 
 
* `$TODO$`: Interesting methodology of thermal drivers of phenology. To be used with phenological data of JMM 

#### Linkage between leaf phenology and earlywood formation [@PerezdeLis2016]
* High correlations were found between budburst and stem maduration phases. It may be due to the fact that expanding leaves are major sources of auxin indole-3-acetic acid (IAA), a primary hormone promoting vascular differentiaion. 
* Leaf unfolding in ring-porous species occurs when first-formed vessels are already expanding, evidencing that auxin supply from growing leaves is not required for triggering cell division and vascular differentiation. Endogenous auxin levels in the dormant cambium, probably provided in winter by either dormant or swelling buds may induce xylogenesis due to higher cell sensitivity to auxin in ring porous species. 
* Ring-porous trees yearly restore their photosynthetic apparatus and hydraulic architecture using exclusively carbon reserves from the previous season. This is particularly true for *Q. pyrenaica* whose leaves were not fully expanded until the end of earlywood formation. 

#### Spring phenology
* Phenological sensitivity to temperature is specific-dependent (see Vitasse et al. 2009 in [@PerezdeLis2016]) 

* A delayed leaf appearance is assumed to be an adaptive response to avoid damage by late frost events (see Vitasse et al. 2014 in [@PerezdeLis2016]) as could be the case of Q. pyrenaica. 

#### Phenology-dependent hydraulic features of EV 
* Climate signals in multi-decadal tree rings series indicate that vessel traits in ring-porous species are mostly influenced by climatic conditions in two physiological distinc periods: during the previous year and at the onset of cambial activity. `$TODO$`{.ruby} `$TODO$` : Relation with lag effects of the drought 

* **Previous summer rainfall** has been stated as the most relevant climatic factor determining vessel size rather than temperature in winter and spring (see González-González et al. 2014; 2015 in [@PerezdeLis2016]). Moisture availability was reported to be the most limiting factor driving radial growth in Iberian *Q. pyrenaica* populations (see Gea-Izquierdo and Cañellas 2014). :arrow_right: Vessel size could be more dependent on environmental signals operating at time windows that are different from those of vessel enlargement, such as precipitation during the previous growing season. 
* Formation of narrower vessels is considered an adaptive response of trees to water stress in ring-porous species. It could be somewhat triggered by declining carbon gain after severe droughts, due to reliance of ring-porous oaks on the reserves of the previous year for earlywood formation and canopy development 






## References 



