---
title: "R packages used"
output: word_document
bibliography: ../pkg-refs.bib
---

- base [@base]
- auxiliar [@auxiliar]
- binaryLogic [@binaryLogic]
- boot [@boot]
- broom [@broom]
- car [@car]
- checkpoint [@checkpoint]
- corrplot [@corrplot]
- devtools [@devtools]
- dplR [@dplR]
- dplyr [@dplyr]
- effects [@effects]
- flexdashboard [@flexdashboard]
- ggcorrplot [@ggcorrplot]
- ggplot2 [@ggplot2]
- ggrepel [@ggrepel]
- grateful [@grateful]
- grid [@grid]
- gridExtra [@gridExtra]
- gtable [@gtable]
- here [@here]
- kableExtra [@kableExtra]
- knitr [@knitr]
- latticeExtra [@latticeExtra]
- leaflet [@leaflet]
- loadeR [@loadeR]
- lsmeans [@lsmeans]
- lubridate [@lubridate]
- MASS [@MASS]
- multcomp [@multcomp]
- pander [@pander]
- patchwork [@patchwork]
- plotly [@plotly]
- plyr [@plyr]
- purrr [@purrr]
- raster [@raster]
- rasterVis [@rasterVis]
- rcompanion [@rcompanion]
- RCurl [@RCurl]
- readr [@readr]
- reshape2 [@reshape2]
- rgdal [@rgdal]
- rgeos [@rgeos]
- rowr [@rowr]
- scales [@scales]
- sp [@sp]
- SPEI [@SPEI]
- stats [@stats]
- stringr [@stringr]
- tidyverse [@tidyverse]
- TRADER [@TRADER]
- transformeR [@transformeR]
- treeclim [@treeclim]
- trend [@trend]
- WRS2 [@WRS2]
- XML [@XML]
- zoo [@zoo]

## References
