---
title: "Notas Historicas"
author: "AJ Perez-Luque (@ajpelu)"
date: "2017"
output:  
  md_document:
    toc: true
    variant: markdown_github
bibliography: ../../refs/references.bib
csl: ../../refs/ecology.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Actuaciones forestales

Revision bbdd actuaciones forestales

* PROYECTO DE ACTUACIONES EN LA DEHESA DE SAN JUAN. FINCA PÚBLICA DEL P.N. SIERRA NEVADA 
	* exp. CMA. 10050119
	* Director Javier Cano 
	* cod. base de datos 36 

* MEJORA SELVÍCOLA EN LA DEHESA DE SAN JUAN
	* Tragsa
	* Director Juan Montoya
	* exp. S/N 21/09 
	* FECHA?? 
	* cod. base de datos 105 

* GESTIÓN ADAPTATIVA DE MASAS DE QUERCUS PYRENAICA EN LA DEHESA DE SAN JUAN
	* TRAGSA
	* NO FECHA
	* cod. base de datos 107 
	* ?? 

* REGENERACIÓN DE ECOSISTEMAS EN EL PARQUE NATURAL DE SIERRA NEVADA
	* director ANDRÉS CASTILLO FERNAUD 
	* Fecha fin ?? 
	* cod. base de datos 70
	* obs. En la base de datos aparece que la actuación es sobre Encinar, pero la espacialización es sobrel Robledal de Cáñar 
	* En la bd de proyectos en obs. aparece en el campo OBSERV: Aclareos dejando en todo una densidad mínima de 1200 pies/ha. Resalveo no reduciendo más del 20% de FCC.

* RESTAURACIÓN DE HÁBITATS DE ROBLEDAL Y ENCINAR EN EL ESPACIO NATURAL DE SIERRA NEVADA
	* Fecha fin ?? 
	* cod. base de datos 61
	* No fecha en proyecto, pero si en actuación (2007) ?? 
	* Es del que habla M. Valbuena?? 

* RESTAURACION ZONAS INCENDIADAS EN MONTES MUNICIPALES DE SIERRA NEVADA
	* JAVIER NAVARRO
	* fecha fin? 
	* cod. base de datos 53
	
	
### datos 
type, date_start, date_end, site, zona, id_proyecto, id_pols, obs
resalveo 50 percentage, 01/10/2005, 31/08/2006, sj, hortichuela, 36, 1533|1534, no obs
clara-clareo 100 percentage,,,sj, hortichuela ctjo. hoyo, 105, 3401, no fecha| densidad de poda 20 pies / ha
resalveo 50 percentage, 01/06/1995, , ca, El Robledal | entre estacion y cortijo nevazo, 70, 2354, aclareos dejando una densidad mínima de 1200 pies / ha | Resalveo no reduciendo mas del 20 % de FCC 
resalveo 50 percentage, 01/01/2007,,ca, El Robledal | entre estacion y cortijo nevazo, 61, 1813, 
roza selectiva matorral 50 percentage, 01/01/2007,,ca, El Robledal | entre estacion y cortijo nevazo, 61, 1813, idem anterior
resalveo 50 percentage,,,ca, buffer carril entre estacion y carril que sube (por donde subimos),, 1870, pone que es resalveo de encinar
roza selectiva matorral 50 percentage,,,ca, buffer carril entre estacion y carril que sube (por donde subimos),, 1870, pone que es roza de matorral | idem anterior
resalveo 50 percentage,,,ca, buffer carril entre estacion y carril treeline,, 1871, pone que es resalveo de encinar
roza selectiva matorral 50 percentage,,,ca, buffer carril entre estacion y carril treeline,, 1871, pone que es roza de matorral | idem anterior
resalveo 50 percentage,01/01/2008,,ca,zona derecha estacion,53, 1873, restauracion zonas incendiadas (incendio??)
roza selectiva matorral 50 percentage,01/01/2008,,ca,zona derecha estacion,53, 1873, restauracion zonas incendiadas (incendio??)
resalveo 50 percentage,,,ca,zona derecha estacion bajo hacia ca,, 1874, restauracion zonas incendiadas (incendio??)
roza selectiva matorral 50 percentage,,,ca,zona derecha estacion bajo hacia ca,, 1874, restauracion zonas incendiadas (incendio??) 





# Minería

## Mina La Probadora
* Antigua mina de cobre explotada desde finales del siglo XIX (1890) hasta 1957.
* Situada en el cortijo de su mismo nombre 
* Actualmente ruinas de antigua fundición 
* En su época de explotación, los materiales eran llevados a lomos de caballerías hasta la estación del tranvía de Sierra Nevada, que dispuso de un vagón especial para el transporte del mineral hasta Granada.

* Óxidos de Hierro
* Mineralización de cobre 

* Hay una galería (la mas grande) que esta entibada 


# Tranvía
* En 1941 había una propuesta de ampliación del tranvía de Sierra Nevada, desde el Maitena hasta la Estrella. Ver plano de José Pérez-Pozuelo (Colección Miguel Giménez Yanguas) en Luces de Sulayr


# Ganado
## San Juan 

* Fuente: MIGRAME y FB. Entrevista a José Luis Pimentel (617851906) (guarda del P Nacional, hijo del guarda de la finca privada Dehesa de San Juan ...) Source: /Users/ajpelu/Desktop/2012_FB_recopilacion_historica/Obj_2_Usos_Suelo_Aprovechamientos/Act_212_Asociaciones profesionales/GuejarSierra

Recopilación información ganadera (from MIGRAME)

Respecto a los lugares concretos en los que, en principio, se va a desarrollar el proyecto se han recopilado los datos de detalle de la carga ganadera y su evolución a lo largo de la serie del 56 hasta la actualidad, así como su variación estacional. También se ha espacializado la información. Los lugares son: robledal del San Juan, el de Cañar y la Dehesa del Camarate. En Cañar ha sido a través de los pliegos y de entrevistas con pastores, técnicos del ayuntamiento  y al alcalde. En San Juan, a través de entrevista con el guarda cuando era privada y a través de los pliegos en el periodo en el que pasó a ser de Parques Nacionales. En el Camarate a través de entrevista con el guarda de las dos zonas (privada y la ahora pública), que antes era una sola.
Los datos de la totalidad de montes públicos tanto de la junta de Andalucía, como de ayuntamientos y del ministerio de medio ambiente, los he conseguido pero de manera agregada. Estoy intentando por tres vías diferentes hacernos con ellos: que nos den de alta como usuarios en la aplicación SAGA, que gestiona los aprovechamientos, solicitarlos a la Rediam (que ya he cursado) y si no da resultado esto, buscar gente del parque que esté dada de alta en la aplicación y que nos deje pasarnos por allí a bichearla.




# Links 

## Minería 
* http://www.mtiblog.com/2012/01/mina-la-probadora-guejar-sierra-granada.html 
* Plano Topográfico-Minero de una parte de Sierra Nevada [Material cartográfico]: Término de Güéjar Sierra, Provincia de Granada. 1858 http://www.ign.es/fondoscartograficos/ 
* http://www.foro-minerales.com/forum/viewtopic.php?p=69374 
* La Probadora: http://mining-andaluz.de/?page_id=4025 

## References 
