---
output:
  word_document:
    reference_docx: ../../templates/template_tables_portrait.docx
bibliography: ../../refs/references.bib
csl: ../../refs/ecology.csl
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning = FALSE)
```


```{r}
library("tidyverse")
library("here")
library("dplyr")
library("flextable")

```


##### 
**Table S3.** Drought events for Sierra Nevada based on SPEI index (12 months scale). See methods for details.

```{r}
# peores sequias 
dy <- read.csv(file=here::here('data/sequias', 'severe_spei12.csv'), header=TRUE)
dy <- dy %>% arrange(desc(d_duration)) %>% 
  arrange(desc(d_severity))
# solamente aquellos mayor de 2 meses 
dys <- dy %>% 
  filter(d_duration > 2) %>%  
  mutate(year = ifelse(minyear == maxyear, 
                       minyear, 
                       paste0(minyear, '-', maxyear))) %>% 
  dplyr::select(-minyear, -maxyear, -cat, -month_peak) %>% 
  as.data.frame() 


td <- regulartable(dys, col_keys = names(dys))
td <- td %>% 
  set_header_labels(d_duration = "Duration \n(months)", d_intensity = "Intensity", 
                   d_severity = "Severity", lowest_spei = "Lowest \nSPEI", rangeDate = "Months", year = "Year") %>% 
  align(align = "center", part ="all") %>% 
  bold(part = 'header') %>% 
  fontsize(part = "header", size = 10) %>%
  fontsize(part = "body", size = 9) 
td
```
