---
output:
  word_document: 
    reference_docx: ../../templates/template_tables_portrait.docx
bibliography: ../../refs/references.bib
csl: ../../refs/ecosystems.csl
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning = FALSE)
```


```{r}
library(tidyverse)
library(here)
library(pander)
library(kableExtra)
library(knitr)
library(dplyr)
library(flextable)
library('officer')
```


**Table S2.** Robust measures of central tendency of resilience indices for greenness (EVI) and tree growth (BAI), grouped by drought events, site, and interaction. Measures of central tendency are M-estimators based on Huber's Psi (see Material and methods).In parentheses are the 95% confidence intervals using 3000 bootstraps. *Total* corresponds to the average of 2005 and 2012.

```{r}

# Number of digits 
d <- 3

eraw <- df <- read.csv(here::here("/out/anovas_resilience/huber_evi", "robust_mhuber_agg.csv"), header = TRUE)
e <- eraw %>% 
  rename(variables = var) %>% 
  mutate_at(.vars = c("M.Huber", "lower.ci", "upper.ci"), funs(round(., d))) %>% 
  dplyr::select(c(-n, -Letter)) 

# Datos agrupados para todos los sitios 
eraw_a <- read.csv(here::here("/out/anovas_resilience/huber_evi", "robust_mhuber_agg_a.csv"), header = TRUE)
e_a <- eraw_a %>% 
  rename(variables = var)  %>% 
  mutate_at(.vars = c("M.Huber", "lower.ci", "upper.ci"), funs(round(., d))) %>% 
  dplyr::select(c(-n, -Letter)) %>%  
  mutate(site = "z_all") 

# Datos agrupados para todos los sitios 
eraw_b <- read.csv(here::here("/out/anovas_resilience/huber_evi", "robust_mhuber_agg_b.csv"), header = TRUE)

e_b <- eraw_b %>% 
  rename(variables = var)  %>% 
  dplyr::select(c(-n, -Letter)) %>%  
  mutate_at(.vars = c("M.Huber", "lower.ci", "upper.ci"), funs(round(., d))) %>%
  mutate(disturb_year = 2099) 


emm <- e %>% 
  bind_rows(e_a) %>%
  bind_rows(e_b) %>% 
  unite("v", c("disturb_year","variables"), sep="") 
  
emm_MH <- emm %>% 
  dplyr::select(v, site, M.Huber) %>% 
  mutate(M.Huber = as.character(format(M.Huber, digits = d))) %>% 
  spread(v, M.Huber) %>% 
  mutate(what = 'mh')

emm_CI <- emm %>% 
  dplyr::select(-M.Huber) %>% 
  mutate_at(.vars = c("lower.ci","upper.ci"), funs(format(., digits = d))) %>%  
  unite("ci", c("lower.ci","upper.ci"), sep=" - ") %>% 
  mutate(ci = paste0('(', ci, ')')) %>% 
  spread(v,ci) %>% mutate(what = 'ci')

emi <- bind_rows(emm_MH, emm_CI) %>% arrange(site) %>% 
  mutate(site = case_when(
    site == 'z_all' ~ "All",
    site == 'N' ~ "Northern slope", 
    site == 'S' ~ "Southern slope"),
    var = 'EVI') 


# BAI
braw <- read.csv(here::here("/out/anovas_resilience/huber_bai", "robust_mhuber.csv"), header = TRUE)

b <- braw %>% 
  rename(variables = var) %>% 
  mutate_at(.vars = c("M.Huber", "lower.ci", "upper.ci"), funs(round(., d))) %>% 
  dplyr::select(c(-n, -MonoLetter, -Letter, -var_sorted)) 

# Datos agrupados para todos los sitios 
braw_a <- read.csv(here::here("/out/anovas_resilience/huber_bai", "robust_mhuber_agg_a.csv"), header = TRUE)

b_a <- braw_a %>% 
  rename(variables = var)  %>% 
  mutate_at(.vars = c("M.Huber", "lower.ci", "upper.ci"), funs(round(., d))) %>% 
  dplyr::select(-n, -Letter) %>%  
  mutate(site = "z_all")
  
# Datos agrupados para todos los sitios 
braw_b <- read.csv(here::here("/out/anovas_resilience/huber_bai", "robust_mhuber_agg_b.csv"), header = TRUE)

b_b <- braw_b %>% 
  rename(variables = var)  %>% 
  mutate_at(.vars = c("M.Huber", "lower.ci", "upper.ci"), funs(round(., d))) %>% 
  dplyr::select(-n, -Letter) %>% 
  mutate(disturb_year = 2099) 

bmm <- b %>% 
  bind_rows(b_a) %>%
  bind_rows(b_b) %>% 
  unite("v", c("disturb_year","variables"), sep="") 
  
bmm_MH <- bmm %>% 
  dplyr::select(v, site, M.Huber) %>% 
  mutate(M.Huber = as.character(format(M.Huber, digits = d))) %>% 
  spread(v, M.Huber) %>% 
  mutate(what = 'mh')

bmm_CI <- bmm %>% 
  dplyr::select(-M.Huber) %>% 
  mutate_at(.vars = c("lower.ci","upper.ci"), funs(format(., digits = d))) %>%  
  unite("ci", c("lower.ci","upper.ci"), sep=" - ") %>% 
  mutate(ci = paste0('(', ci, ')')) %>% 
  spread(v,ci) %>% mutate(what = 'ci')


bmi <- bind_rows(bmm_MH, bmm_CI) %>% arrange(site) %>% 
  mutate(site = case_when(
    site == 'z_all' ~ "All",
    site == 'caH' ~ 'CA-High', 
    site == 'caL' ~ 'CA-Low',
    site == 'SJ' ~ 'SJ'), 
    var = 'BAI') 


latabla <- emi %>% bind_rows(bmi)



# CREATE TABLE 

# Define borders
big_border = fp_border(width = 2)
std_border = fp_border(width = 1)

mt <- regulartable(latabla,
                   col_keys = c("var","site","c1", "2005rt","2005rc","2005rs", "c2",
                                "2012rt","2012rc","2012rs","c3","2099rt","2099rc", "2099rs"))
mt <- mt %>% 
  # Header 
  set_header_labels('var' = "Variable", site = "Sites", 
                        '2005rt' = "Resistance", '2005rc' = "Recovery", '2005rs' = "Resilience",
                        '2012rt' = "Resistance", '2012rc' = "Recovery", '2012rs' = "Resilience",
                        '2099rt' = "Resistance", '2099rc' = "Recovery", '2099rs' = "Resilience") %>% 
  add_header(var = "", site="", '2005rt' = "2005", '2005rc' = "2005", '2005rs' = "2005",'2012rt' = "2012", '2012rc' = "2012", '2012rs' = "2012",
                        '2099rt' = "Total", '2099rc' = "Total", '2099rs' = "Total", top = TRUE) %>% 
  merge_at(i = 1, j =c(4:7) , part = "header") %>% 
  merge_at(i = 1, j =c(8:10) , part = "header") %>%
  merge_at(i=1, j =c(12:14), part = "header") %>% 
  align(align = "center", part = "header") %>% 
  bold(part = 'header') %>% 
  fontsize(part = "header", size = 9) %>% 
  
  # General format 
  fontsize(part = "body", size = 8) %>% 
  autofit(add_w = 0, add_h = 0) %>% 
  empty_blanks() %>% 
  align(align = "center") %>% 
  
  # Borders 
  border_remove() %>% 
  hline(i = 1:2, border = big_border, part = "header") %>% 
  hline(i = 6, border = big_border, part = "body") %>% 
  vline(j = c(2,6,10), border = big_border, part = "all") %>% 
  hline(i = c(2,4,8,10,12), border = std_border, part = "body") %>% 
  

  # First column 
  merge_v(~var) %>% 
  merge_v(~site) %>% 
  italic(j= c(1,2), part = "body") %>% 
  bold(j=1, part = "body")

mt 
```
  




