---
output:
  word_document:
    fig_caption: yes
    highlight: null
    reference_docx: ../../templates/template_pagebreak.docx
bibliography: ../../refs/references.bib
csl: ../../refs/ecology.csl
---


```{r, include=FALSE}
options(knitr.duplicate.label = 'allow')
```

```{r child = 'location_map.Rmd'}
```

##### 

```{r child = 'std_anomalies.Rmd'}
```

#####

```{r child = 'browning.Rmd'}
```

##### 

```{r child = 'bai_cronos.Rmd'}
```

##### 

```{r child = 'growth_changes.Rmd'}
```

#####

```{r child = 'resilience_long_term.Rmd'}
```

#####

```{r child = 'resilience_metrics.Rmd'}
```


#####

```{r child = 'ring_climate.Rmd'}
```


##### 

```{r child = 'cumulative_prec.Rmd'}
```

##### 

```{r child = 'plot_spei12.Rmd'}
```


#####

```{r child = 'residual_chronos.Rmd'}
```


##### 

```{r child = 'gc_perc_trees.Rmd'}
```



##### 

```{r child = 'corr_plot_years.Rmd'}
```


##### 

```{r child = 'correla_boot_sites.Rmd'}
```


##### 

```{r child = 'evi_vs_severe_droughts.Rmd'}
```
