---
output:
  word_document
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning = FALSE)
```

```{r pkg}
library("tidyverse")
library("here")
library("scales")
library("viridis") # colours 
library("ggthemes") # colours 
source(here::here('/script/R/custom_functions.R'))
```


**Figure 3.** Percentage of pixels showing browning, greening or no-changes during the 2005 and 2012 drought events according to EVI standardized anomalies. See main text for an explanation of greening and browning.  

```{r}
df <- read.csv(file=here::here('/out/anomalies/evi' ,'percen_browing_greening.csv'), header=TRUE)

df <- df %>% add_row(clu_pop2 = 'Northern slope',
                             type = 'greening',
                             count_clu = 0, per = 0.00, y = 2005) 

df <- df %>% mutate(type = stringr::str_to_title(type))
```

```{r plot}
per_pixels_green <- df %>% 
  ggplot(aes(x=type, y=per, fill=as.factor(y))) + 
  geom_bar(stat = 'identity', position = "dodge") + 
  geom_text(aes(label = paste0(per, " %")), position=position_dodge(width=0.9), hjust=-.1, size=2, angle = 90) + 
  facet_wrap(~clu_pop2) + 
  theme_bw() + xlab('') + ylab('Frequency of pixels (%)') +
  theme(strip.background = element_rect(colour = "white", fill = "white"),
        strip.text = element_text(size = 7), 
        axis.title.y = element_text(size = 7, face = 'bold'),
        axis.text = element_text(size = 7),
        panel.grid = element_blank(),
        legend.position = 'bottom', 
        legend.text = element_text(size = 7), 
        legend.box.spacing = unit(0.01, "cm"))+
  labs(fill = 'Drought event') + 
  scale_fill_colorblind() + 
  scale_y_continuous(limits = c(0, 110), breaks = c(0, 25, 50, 75, 100)) +
  guides(fill = guide_legend(title.theme = element_text(size = 7)))
```

```{r out_plot, fig.width= 4, dpi = 300, out.width = 0.8}
per_pixels_green
```

```{r}
saveImage(per_pixels_green, path="./man/figures/svg/", dpi=300, w=14, h=14, fig= "fig_3", u = "cm") 
```


