---
output: 
  word_document
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning = FALSE)
```

```{r load_pkg}
library("tidyverse")
library("here")
library("scales")

library("grid")
library("gridExtra")
library("patchwork")
library("ggcorrplot")
library("stringr")
library("pander")
library("lemon")
source(here::here('/script/R/custom_functions.R'))
```



```{r data}
cro_rwi <- read.csv(here("data/cronos_medias", "cronos_sites_rwi.csv"), header = TRUE, sep = ',')
year_cutoffs <- read.csv(here("data/cronos_medias", "cronos_sites_rwi_year_cutoffs.csv"), header = TRUE, sep = ',')
year_sampledepth <- read.csv(here("data/cronos_medias", "cronos_sites_rwi_year_sampledepth.csv"), header = TRUE, sep = ',')

# Reorder 
cro_rwi <- cro_rwi %>% mutate(site_sorted = 
                                recode_factor(site,
                                              "caH" = "0_caH", 
                                              "caL" = "1_caL", "sj" = "2_sj"))

year_cutoffs <- year_cutoffs %>% mutate(site_sorted = 
                                recode_factor(site,
                                              "caH" = "0_caH", 
                                              "caL" = "1_caL", "sj" = "2_sj"))



year_sampledepth <- year_sampledepth %>% mutate(site_sorted = 
                                   recode_factor(site,
                                              "caH" = "0_caH", 
                                              "caL" = "1_caL", "sj" = "2_sj"))


# peores sequias 
dy <- read.csv(file=here::here('data/sequias', 'severe_spei12.csv'), header=TRUE)
dy <- dy %>% arrange(desc(d_duration))
# solamente aquellos mayor de 2 meses 
dys <- dy %>% filter(d_duration > 2) %>% as.data.frame() 
dys <- dys[,'maxyear'] 
```

```{r data_aux}
# Mayores y menores crecimientos 
# top10  
top10pos50 <- cro_rwi %>% filter(year > 1950) %>% arrange_(~desc(res)) %>% group_by_(~site) %>%  slice(1:10)
top10neg50 <- cro_rwi %>% filter(year > 1950) %>% arrange_(~res) %>% group_by_(~site) %>%  slice(1:10)
top10pos <- cro_rwi %>% arrange_(~desc(res)) %>% group_by_(~site) %>%  slice(1:10)
top10neg <- cro_rwi %>% arrange_(~res) %>% group_by_(~site) %>%  slice(1:10)
```

```{r plot_rwi}

label_site <- c("2_sj" = "SJ",
                "0_caH" = "CA-High",
                "1_caL" = "CA-Low")

# 
plot_rwi_crono <- ggplot(cro_rwi, aes(x=year, y=res, colour=site)) +
  theme_bw() + 
  theme(panel.grid = element_blank(), 
        strip.background = element_rect(fill = "white"),
        strip.text = element_text(face="bold", size=9), 
        # strip.text = element_blank(), 
        axis.text = element_text(size=8), 
        axis.title = element_text(face="bold", size=9), 
        legend.position = "none") + 
  geom_hline(yintercept = 1, colour = "grey") + 
  geom_line(size=.8) + scale_y_continuous(breaks = seq(0.4,1.8, 0.2)) +
  facet_wrap(~site_sorted, scales = "free_x", ncol = 1,
             labeller = as_labeller(label_site)) + 
  ylab("Ring width index") + xlab("Year") + 
  geom_vline(aes(xintercept = year), data = year_cutoffs,  linetype = "dashed", colour='red') + 
  # geom_vline(aes(xintercept = year), data = year_sampledepth,  linetype = "dashed", colour='blue') +
  geom_vline(xintercept = dys, linetype = "dotted") + 
  # geom_vline(xintercept = dys, linetype = "dotted") + 
  scale_x_continuous(limits = c(1819, 2016), 
                     breaks= seq(1820, 2020, by=20)) +
  scale_colour_manual(values = colores_den)
  


```


**Figure S3.** Residual tree-ring chronologies obtained for the *Q. pyrenaica* sites. Dashed red lines indicate the start of the reliable period (EPS > 0.85). Dotted black lines showing the severe drought years identified in our climatic data (Table S3 and Figure S1). 

```{r plot_out, fig.height=4.5, dpi = 300, out.width = 0.8} 
plot_rwi_crono  
```

```{r}
# SAVE as eps 
saveImage(plot_rwi_crono , path="./man/figures/svg/", dpi=300, w=25, h=14, fig= "fig_s3", u = "cm") 
```
