---
output:
  word_document
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning = FALSE)
```

```{r load_pkg}
library("tidyverse")
library("here")
library("scales")
library("patchwork")
library("ggrepel")
library("broom")
library("cowplot")
```



```{r data}
df <- read.csv(file=here::here('/out/bai_resiliences_severes' ,'resiliences_bai_droughts.csv'), header=TRUE)

# peores sequias 
dy <- read.csv(file=here::here('data/sequias', 'severe_spei12.csv'), header=TRUE)
dy <- dy %>% arrange(desc(d_duration))
# solamente aquellos mayor de 2 meses 
dys <- dy %>% filter(d_duration > 2) %>% filter(maxyear > 1940 ) %>% as.data.frame() 
# dys <- dys[,'maxyear'] 

sdf <- df %>% 
  filter(samps >= 10) %>% 
  group_by(disturb_year) %>% 
  summarise_at(c("rt_mean", "rs_mean", "rc_mean", "rrs_mean"), 
               funs(mean(., na.rm = TRUE), sd(., na.rm=TRUE),se=sd(., na.rm=TRUE)/sqrt(n()))) %>% 
  inner_join(dy, by=c("disturb_year" = "maxyear")) 
```


```{r plot_functions}
#https://gist.github.com/ottadini/6882677 
lm_eqn = function(m) {
  # Displays regression line equation and R^2 value on plot
  # Usage:
  # p + annotate("text", x=25, y=300, label=lm_eqn(lm(y ~ x, df)), parse=TRUE)
  
  # l <- list(#a = format(coef(m)[1], digits = 2),
  #           # b = format(abs(coef(m)[2]), digits = 2),
  #           rvalue = format(summary(m)$r.squared, digits = 3),
  #           pvalue = format(summary(m)$coefficients[2,'Pr(>|t|)'],3));
  
  # eq <- substitute(~~italic(r)^2~"="~r2,l[1], "p=",l[2])
  
  eq2 <- substitute(~~italic(r)^2~"="~rvalue*","~italic(p)~"="~pvalue,  
                    list(rvalue = format(summary(m)$r.squared, digits = 3), 
                         pvalue = format(summary(m)$coefficients[2,4], digits = 3)))
  
  
  # if (coef(m)[2] >= 0)  {
  #   # eq <- substitute(italic(y) == a + b %.% italic(x)*","~~italic(r)^2~"="~r2,l)
  #   eq <- substitute(~~italic(r)^2~"="~r2,l[1], "p=",l[2])
  # } else {
  #   # eq <- substitute(italic(y) == a - b %.% italic(x)*","~~italic(r)^2~"="~r2,l) 
  #   eq <- substitute(~~italic(r)^2~"="~r2,l)
  # }
  
  as.character(as.expression(eq2));                 
}





plotrel <- function(df, v, x, label, coordX_eq, coordY_eq, titulo, ...){
  require(ggplot2)
  require(ggrepel)

  formulita <- as.formula(paste0(v, "_mean_mean ~", x)) 
  
  yerrbar <- aes_string(ymin = paste0(v, "_mean_mean - ",  v, "_mean_se"), 
                        ymax = paste0(v, "_mean_mean + ",  v, "_mean_se")) 
  
  ggplot(df, aes_string(y=paste0(v, "_mean_mean"), x=x, label=label)) + 
    geom_smooth(method='lm', se=FALSE, colour="gray") +
    geom_errorbar(mapping = yerrbar) + 
    geom_point(size=1.5, pch = 21, colour="black", fill="white") + 
    theme_bw() + 
    geom_text_repel(nudge_x = 0.5, size = 3) + 
    annotate("text", x = coordX_eq, y = coordY_eq, 
             label=lm_eqn(lm(formulita, df)), parse=TRUE, 
             size = 3, fontface = "bold", hjust="left") +
    ggtitle(titulo) + 
    theme(plot.title = element_text(size = 11, face = "bold.italic"),
          panel.grid = element_blank(), 
          axis.text.y = element_text(size=9),
          axis.text.x = element_text(size=9),
          axis.title = element_text(size = 10))

  }

```


```{r plot_rt}
sevRt <- plotrel(sdf, v = "rt", x = 'd_severity', label = 'disturb_year',
                 coordX_eq = 6, coordY_eq = 0.5, titulo = "Rt") +
  xlab('') + ylab('') +
  theme(plot.margin = margin(r=-0.7, l=0, t=0, b=0, "pt"))

```


```{r plot_rs}
sevRs <- plotrel(sdf, v = "rs", x = 'd_severity', label = 'disturb_year',
                 coordX_eq = 6, coordY_eq = 0.5, titulo = "Rs") + 
  xlab('') + ylab('') +
  theme(plot.margin = margin(r=0, l=-0.7, t=0, b=0, "pt"))
```

```{r plot_rc}
sevRc <- plotrel(sdf, v = "rc", x = 'd_severity', label = 'disturb_year',
                 coordX_eq = 6, coordY_eq = 0.5, titulo = "Rc") +
  xlab("Drought Severity") + ylab('') +
  theme(plot.margin = margin(r=-0.7, l=-0.7, t=0, b=0, "pt"))
```


```{r plot_join, eval=FALSE, echo=FALSE}
res_long_term <- sevRt + sevRc + sevRs + 
  plot_layout(nrow = 1) 
```

**Figure 6.** Resilience metrics of the tree-growth for the most severe drought events (as from Table S3). *Left*: Resistance (*Rt*); *Center*: Recovery (*Rc*); *Right*: Resilience (*Rs*). Points indicate average of resilience metrics for all populations. Error bar corresponds standard error. Resilience metrics were computed for each population (sample depth > 10) and drought event.


```{r plot_out, fig.width=6, dpi = 300, out.width = 0.8, eval=FALSE, echo=FALSE}
res_long_term
```


```{r, eval=FALSE, echo=FALSE}
dff <- sdf %>% 
  dplyr::select(d_severity, rt_mean_mean, rs_mean_mean, rc_mean_mean) %>% 
  gather(key = res_metric, value,c(rt_mean_mean,rs_mean_mean,rc_mean_mean))

nested_df <- group_by(dff, res_metric) %>% nest()

fit_model <- function(x){
  lm(value ~ d_severity, data = x)
}

nested_df <- nested_df %>% 
  mutate(model = map(data, fit_model))


# Get R2 and p.value 
get_rsq <- function(mod) glance(mod)$r.squared
get_pvalue <- function(mod) glance(mod)$p.value


nested_df <- nested_df %>% 
  mutate(r.squared = map_dbl(model, get_rsq),
         pvalue = map_dbl(model, get_pvalue))

```


```{r}
library("purrr")

sdfsite <- df %>% 
  filter(samps >= 10) %>% 
  group_by(disturb_year, site) %>% 
  filter(disturb_year > 1950) %>% 
  summarise_at(c("rt_mean", "rs_mean", "rc_mean", "rrs_mean"), 
               funs(mean(., na.rm = TRUE), sd(., na.rm=TRUE),se=sd(., na.rm=TRUE)/sqrt(n()))) %>% 
  inner_join(dy, by=c("disturb_year" = "maxyear")) 


plotrelsite <- function(df, v, x, label, site, titulo, coord_eqX, ...){
  require(ggplot2)
  require(ggrepel)
  require(purrr)

  formulita <- as.formula(paste0(v, "_mean_mean ~", x)) 
  
  eqns <- df %>% split(.$site) %>% 
    map(~ lm(formulita, data = .)) %>%
    map(lm_eqn) %>% 
    do.call(rbind, .) %>%
    as.data.frame() %>%
    set_names("equation") %>%
    mutate(site = rownames(.))
  
  ggplot(df, 
         aes_string(y=paste0(v, "_mean_mean"), x=x, label=label, colour=site, fill=site)) +
    geom_smooth(method='lm', se=FALSE, aes(group=1), colour='gray',  size = 1) + # linetype = "dotted",
    geom_smooth(method='lm', se=FALSE) + 
    geom_point(size=1.5, pch = 21) + 
    theme_bw() + 
    geom_text_repel(nudge_x = 0.5, size = 2, show.legend = FALSE) + 
    ggtitle(titulo) + 
    theme(plot.title = element_text(size = 11, face = "bold.italic"),
          panel.grid = element_blank(), 
          axis.text.y = element_text(size=9),
          axis.text.x = element_text(size=9),
          axis.title = element_text(size = 10)) +
    geom_text_repel(data = eqns, aes(x = coord_eqX, y = Inf, label = equation), 
                    direction = "y", 
                    parse = TRUE, segment.size = 0, show.legend = FALSE)

}

```



```{r}
sevRt_site <- plotrelsite(sdfsite, v = "rt", x = 'd_severity', label = 'disturb_year', site = "site",
                 titulo = "Rt", coord_eqX = Inf) +
  xlab('') + ylab('') + xlim(5,25)

# + theme(plot.margin = margin(r=-0.7, l=0, t=0, b=0, "pt"))
```


```{r}
sevRs_site <- plotrelsite(sdfsite, v = "rs", x = 'd_severity', label = 'disturb_year', site = "site",
                 titulo = "Rs", coord_eqX = -Inf) + xlab('') + ylab('') + xlim(5,25)
# theme(plot.margin = margin(r=0, l=-0.7, t=0, b=0, "pt")) 
```


```{r}
sevRc_site <- plotrelsite(sdfsite, v = "rc", x = 'd_severity', label = 'disturb_year', site = "site",
                 titulo = "Rc",  coord_eqX = -Inf) +
  xlab("Drought Severity") + ylab("") + xlim(5,25)
#+ theme(plot.margin = margin(r=-0.7, l=-0.7, t=0, b=0, "pt"))
```


```{r}
res_long_term_sites <- sevRt_site + theme(legend.position="none") +
  sevRc_site + theme(legend.position="bottom") +
  sevRs_site + theme(legend.position = "none") + plot_layout(nrow = 1) 


ggsave(filename = here::here("./man/figures/svg/fig_6.jpg"), 
       dpi = 300,  plot=res_long_term_sites, width=9, height=7)

```

```{r, fig.width=6, dpi = 300, out.width = 0.8}
res_long_term_sites
```






