---
output: 
  word_document
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning = FALSE)
```

```{r load_pkg}
library("tidyverse")
library("here")
library("ggrepel")
library("scales")
library("grid")
library("gridExtra")
library("patchwork")
library("ggcorrplot")
library("stringr")
library("pander")
library("lemon")
library("ggpubr")
source(here::here('/script/R/custom_functions.R'))

```


```{r}
cro_rwi <- read.csv(here("data/cronos_medias", "cronos_sites_rwi.csv"), header = TRUE, sep = ',')
year_cutoffs <- read.csv(here("data/cronos_medias", "cronos_sites_rwi_year_cutoffs.csv"), header = TRUE, sep = ',')
year_sampledepth <- read.csv(here("data/cronos_medias", "cronos_sites_rwi_year_sampledepth.csv"), header = TRUE, sep = ',')

# Reorder 
cro_rwi <- cro_rwi %>% mutate(site_sorted = 
                                recode_factor(site,
                                              "caH" = "0_caH", 
                                              "caL" = "1_caL", "sj" = "2_sj"))

year_cutoffs <- year_cutoffs %>% mutate(site_sorted = 
                                recode_factor(site,
                                              "caH" = "0_caH", 
                                              "caL" = "1_caL", "sj" = "2_sj"))



year_sampledepth <- year_sampledepth %>% mutate(site_sorted = 
                                   recode_factor(site,
                                              "caH" = "0_caH", 
                                              "caL" = "1_caL", "sj" = "2_sj"))


# peores sequias 
dy <- read.csv(file=here::here('data/sequias', 'severe_spei12.csv'), header=TRUE)
dy <- dy %>% arrange(desc(d_duration))
# solamente aquellos mayor de 2 meses 
dys <- dy %>% filter(d_duration > 2) %>% as.data.frame() 
dys <- dys[,'maxyear'] 
```


```{r plot_rwi}
label_site <- c("2_sj" = "SJ",
                "0_caH" = "CA-High",
                "1_caL" = "CA-Low")

# 
plot_rwi_crono <- ggplot(cro_rwi, aes(x=year, y=res, colour=site)) +
  theme_bw() + 
  theme(panel.grid = element_blank(), 
        strip.background = element_rect(fill = "white"),
        strip.text = element_text(face="bold", size=9), 
        # strip.text = element_blank(), 
        axis.text = element_text(size=8), 
        axis.title = element_text(face="bold", size=9), 
        legend.position = "none") + 
  geom_hline(yintercept = 1, colour = "grey") + 
  geom_line(size=.8) + scale_y_continuous(breaks = seq(0.4,1.8, 0.2)) +
  facet_wrap(~site_sorted, scales = "free_x", ncol = 1,
             labeller = as_labeller(label_site)) + 
  ylab("Ring width index") + xlab("Year") + 
  geom_vline(aes(xintercept = year), data = year_cutoffs,  linetype = "dashed", colour='red') + 
  # geom_vline(aes(xintercept = year), data = year_sampledepth,  linetype = "dashed", colour='blue') +
  geom_vline(xintercept = dys, linetype = "dotted") + 
  # geom_vline(xintercept = dys, linetype = "dotted") + 
  scale_x_continuous(limits = c(1819, 2016), 
                     breaks= seq(1820, 2020, by=20)) +
  scale_colour_manual(values = colores_den)
  
```




```{r}
gc_treesMed <- read.csv(here("data/disturbance", "disturbance_trees_gc_treshold_median.csv"), header = TRUE, sep = ',')
gc_treesMed50 <- read.csv(here("data/disturbance", "disturbance_trees_gc_treshold_median50.csv"), header = TRUE, sep = ',')


gc_treesMed50 <- gc_treesMed50 %>% mutate(site_sorted = 
                                recode_factor(site,
                                              "gc_caH" = "0_caH", 
                                              "gc_caL" = "1_caL", "gc_sj" = "2_sj"))

label_site <- c("2_sj" = "SJ",
                "0_caH" = "CA-High",
                "1_caL" = "CA-Low")


```

```{r plotGC}

colorpositivo <- c("#104E8B")
colornegativo <- c("#CD3333")

# Get min and max year and round to nearest decade
getBreaks <- function(df, v, by){ 
  x <- seq(round(min(df[v]) / 10)*10, 
           round(max(df[v]) / 10)*10, by= by) 
  x
  }

xrange <- getBreaks(gc_treesMed50, 'year', by=10)
  

dat_text <- data.frame(
  label_site = c("CA-Low","CA-High","SJ"),
  site_sorted = c("0_caH","1_caL","2_sj"),
  year = c(1835, 1835, 1835),
  y = c(90, 90, 90))


pgc_median50 <- gc_treesMed50 %>% 
  filter(total_tree > 2) %>% 
  ggplot() +
  geom_bar(aes(x=year, y=per_pos), fill=colorpositivo, colour=colorpositivo, 
           stat = "identity", position = "dodge") + 
  geom_bar(aes(x=year, y=(-1)*per_neg), fill=colornegativo, colour=colornegativo, 
           stat = "identity", position = "dodge") +
  geom_line(aes(x=year, y=total_tree*2), colour = 'black', size = 0.2) + 
  theme_bw() + ylab('% of trees') + xlab("Year") + 
  geom_hline(yintercept=0, alpha=.4) +
  geom_hline(yintercept=c(50, -50), linetype=2, alpha=.4) +
  scale_x_continuous(breaks = xrange) +
  scale_y_continuous(limits = c(-100, 100), breaks = seq(-100, 100, by = 50),
                     sec.axis = sec_axis(~., name = '# trees', breaks = c(0,15,30))) +
  facet_rep_wrap(~site_sorted, nrow = 3, 
                 repeat.tick.labels = TRUE, labeller = as_labeller(label_site)) +
  geom_text(data= dat_text, aes(label = label_site), 
            x = dat_text$year, y = dat_text$y,
            size = 3, fontface = "bold") + 
  theme(panel.grid = element_blank(), 
        strip.background = element_blank(), 
        strip.text = element_blank(),
        axis.text.y.left = element_text(size=6),
        axis.text.y.right  = element_text(size=5),
        axis.text.x = element_text(size=6),
        axis.title = element_text(size = 9)) 

```


```{r}
s34 <- ggarrange(plot_rwi_crono, pgc_median50,
          labels = c("a", "b"),
          ncol = 1, nrow = 2)
```


```{r}
# SAVE as eps 
saveImage(s34, path="./man/figures/svg/", dpi=300, w=25, h=20, fig= "fig_s2ab", u = "cm") 
```

