---
output:  
  word_document:
    reference_docx: "../../man/template_tables_portrait.docx"
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, echo=FALSE}
library(tidyverse)
library(here)
library(pander)
library(kableExtra)
library(knitr)
library(dplyr)
library(flextable)
```


**Table S1.** Robust measures of central tendency of resilience indices for greenness (EVI) groupped by drought events, site and interaction. Measures of central tendency are M-estimators based on Huber's Psi (see material and methods). 95 % confidence intervals using 3000 bootstrap are included in parentheses. 


```{r, echo = FALSE, warning = FALSE}

# Number of digits 
d <- 3

mraw <- df <- read.csv(here::here("/out/anovas_resilience/huber_evi", "robust_mhuber_agg.csv"), header = TRUE)
m <- mraw %>% 
  rename(variables = var) %>% 
  mutate_at(.vars = c("M.Huber", "lower.ci", "upper.ci"), funs(round(., d))) %>% 
  dplyr::select(c(-n, -Letter)) 

# Datos agrupados para todos los sitios 
mraw_a <- read.csv(here::here("/out/anovas_resilience/huber_evi", "robust_mhuber_agg_a.csv"), header = TRUE)
m_a <- mraw_a %>% 
  rename(variables = var)  %>% 
  mutate_at(.vars = c("M.Huber", "lower.ci", "upper.ci"), funs(round(., d))) %>% 
  dplyr::select(c(-n, -Letter)) %>%  
  mutate(site = "z_all") 

# Datos agrupados para todos los sitios 
mraw_b <- read.csv(here::here("/out/anovas_resilience/huber_evi", "robust_mhuber_agg_b.csv"), header = TRUE)

m_b <- mraw_b %>% 
  rename(variables = var)  %>% 
  dplyr::select(c(-n, -Letter)) %>%  
  mutate_at(.vars = c("M.Huber", "lower.ci", "upper.ci"), funs(round(., d))) %>%
  mutate(disturb_year = 2099) 


mm <- m %>% 
  bind_rows(m_a) %>%
  bind_rows(m_b) %>% 
  unite("v", c("disturb_year","variables"), sep="") 
  
mm_MH <- mm %>% 
  dplyr::select(v, site, M.Huber) %>% 
  mutate(M.Huber = as.character(format(M.Huber, digits = d))) %>% 
  spread(v, M.Huber) %>% 
  mutate(what = 'mh')

mm_CI <- mm %>% 
  dplyr::select(-M.Huber) %>% 
  mutate_at(.vars = c("lower.ci","upper.ci"), funs(format(., digits = d))) %>%  
  unite("ci", c("lower.ci","upper.ci"), sep=" - ") %>% 
  mutate(ci = paste0('(', ci, ')')) %>% 
  spread(v,ci) %>% mutate(what = 'ci')


mi <- bind_rows(mm_MH, mm_CI) %>% arrange(site)

mt <- regulartable(mi,
                   col_keys = c("site","c1", "2005rt","2005rc","2005rs", "c2",
                                "2012rt","2012rc","2012rs","c3","2099rt","2099rc", "2099rs"))

mt <- autofit(mt)
mt <- empty_blanks(mt)
mt <- align(mt, align = "center")
mt <- merge_v(mt, ~site)


mt <- set_header_labels(mt, site = "Site", 
                        '2005rt' = "Resistance", '2005rc' = "Recovery", '2005rs' = "Resilience",
                        '2012rt' = "Resistance", '2012rc' = "Recovery", '2012rs' = "Resilience",
                        '2099rt' = "Resistance", '2099rc' = "Recovery", '2099rs' = "Resilience")
                        
# Add row of labels 
mt <- add_header(mt, site="", '2005rt' = "", '2005rc' = "2005", '2005rs' = "",
                        '2012rt' = "", '2012rc' = "2012", '2012rs' = "",
                        '2099rt' = "", '2099rc' = "", '2099rs' = "")
                 
mt                  
             
```

