---
output:  
  word_document:
    reference_docx: "../../man/template_tables_portrait.docx"
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, echo=FALSE}
library(tidyverse)
library(here)
library(pander)
library(kableExtra)
library(knitr)
library(dplyr)
library(flextable)
```


**Table S2.** Robust measures of central tendency of resilience indices for tree-growth (BAI) groupped by drought events, site and interaction. Measures of central tendency are M-estimators based on Huber's Psi (see material and methods). 95 % confidence intervals using 3000 bootstrap are included in parentheses. 


```{r, echo = FALSE, warning = FALSE}
mraw <- read.csv(here::here("/out/anovas_resilience/huber_bai", "robust_mhuber.csv"), header = TRUE)


m <- mraw %>% 
  filter(var != 'rrs') %>% 
  rename(variables = var)  %>% 
  dplyr::select(c(-n, -Letter, -MonoLetter, -var_sorted)) %>% 
  mutate_at(.vars = c("M.Huber", "lower.ci", "upper.ci"), funs(round(., 3)))






 
 unite("mh", c("M.Huber", "ci"), sep = "\n")


# Datos agrupados para todos los sitios 
mraw_a <- df <- read.csv(here("/out/anovas_resilience/huber_bai", "robust_mhuber_agg_a.csv"), header = TRUE)

m_a <- mraw_a %>% 
  filter(var != 'rrs') %>% 
  rename(variables = var)  %>% 
  dplyr::select(c(-n, -Letter)) %>%  
  unite("mh", c("M.Huber", "ci"), sep = "\n") %>% 
  mutate(site = "z_all") 

# Datos agrupados para todos los sitios 
mraw_b <- df <- read.csv(here("/out/anovas_resilience/huber_bai", "robust_mhuber_agg_b.csv"), header = TRUE)

m_b <- mraw_b %>% 
  filter(var != 'rrs') %>% 
  rename(variables = var)  %>% 
  dplyr::select(c(-n, -Letter)) %>%  
  unite("mh", c("M.Huber", "ci"), sep = "\n") %>%
  mutate(disturb_year = 2099) 


mm <- m %>% 
  bind_rows(m_a) %>%
  bind_rows(m_b) %>% 
  gather(temp, numeros, mh) %>% 
  unite(temp1, c(variables, disturb_year), temp) %>% 
  spread(temp1, numeros, fill = "") 

mm <- mm %>% 
  dplyr::select(site, 
                rt_2005_mh, rc_2005_mh, rs_2005_mh,
                rt_2012_mh, rc_2012_mh, rs_2012_mh,
                rt_2099_mh, rc_2099_mh, rs_2099_mh)

colnames(mm) <- c(" \nsite", "2005\nRt", "2005\nRc", "2005\nRs", "2012\nRt", "2012\nRc", "2012\nRs", "Rt", "Rc", "Rs")
pander(mm, keep.line.breaks = TRUE, split.table = Inf)
```


```{r, echo = FALSE, warning = FALSE, eval = FALSE}

# Este código es para print la tabla anterior en formato pdf latex (ver state_ms)c
### OJO REVISAR 
# ------------------------------

mraw <- df <- read.csv(here("/out/anovas_resilience/huber_bai", "robust_mhuber_agg.csv"), header = TRUE)

m <- mraw %>% 
  filter(var != 'rrs') %>% 
  rename(variables = var)  %>% 
  dplyr::select(c(-n, -Letter)) 


# Datos agrupados para todos los sitios 
mraw_a <- df <- read.csv(here("/out/anovas_resilience/huber_bai", "robust_mhuber_agg_a.csv"), header = TRUE)

m_a <- mraw_a %>% 
  filter(var != 'rrs') %>% 
  rename(variables = var)  %>% 
  dplyr::select(c(-n, -Letter)) %>%  
  mutate(site = "z_all") 

# Datos agrupados para todos los sitios 
mraw_b <- df <- read.csv(here("/out/anovas_resilience/huber_bai", "robust_mhuber_agg_b.csv"), header = TRUE)

m_b <- mraw_b %>% 
  filter(var != 'rrs') %>% 
  rename(variables = var)  %>% 
  dplyr::select(c(-n, -Letter)) %>%  
  mutate(disturb_year = 2099) 


mm <- m %>% 
  bind_rows(m_a) %>%
  bind_rows(m_b) %>% 
  gather(temp, numeros, c(M.Huber, ci)) %>% 
  unite(temp1, c(variables, disturb_year), temp) %>% 
  spread(temp1, numeros, fill = "") 

mm <- mm %>% 
  dplyr::select(site, 
                rc_2005_M.Huber, rc_2005_ci, rt_2005_M.Huber, rt_2005_ci, rs_2005_M.Huber, rs_2005_ci,
                rc_2012_M.Huber, rc_2012_ci, rt_2012_M.Huber, rt_2012_ci, rs_2012_M.Huber, rs_2012_ci,
                rc_2099_M.Huber, rc_2099_ci, rt_2099_M.Huber, rt_2099_ci, rs_2099_M.Huber, rs_2099_ci)


mmt <- mm %>%
   rownames_to_column %>% 
   gather(var, value, -rowname) %>% 
   spread(rowname, value) 

colnames(mmt) <- c("var", "SJ", "caH", "caL", "z_all") 
mmt <- mmt[-19,] 
mmt <- mmt %>% 
  mutate(vars = c(rep("Rc",6), rep("Rt",6), rep("Rs",6)),
         year = c(rep(
           c(rep("2005", 2), 
             rep("2012", 2),
             rep(" ", 2)), 3))) %>% 
  dplyr::select(vars, year, SJ, caH, caL, var)


kable(mmt, 
      format = "latex", booktabs = T) %>% 
  kable_styling(font_size = 6) %>% 
  add_header_above(c("", "", "Northern", "Southern" = 2, "")) 
```




