---
output:  
  word_document:
    reference_docx: "../../man/template_tables_portrait.docx"
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, echo=FALSE}
library(tidyverse)
library(here)
library(pander)
library(kableExtra)
library(knitr)
library(dplyr)
```


**Table 3.** Robust two-way ANOVAs of the resilience metrics of greenness (EVI) and tree-growth (BAI) for the factor drought events (2005 and 2012) and site. 

```{r, echo=FALSE, include = FALSE}
### Table R1_evi
df <- read.csv(here("/out/anovas_resilience/huber_evi", "trimmed_anovas.csv"), header = TRUE)
names(df) <- c('factores', 'F', 'p', 'variables')

dff <- df %>% gather(temp, numeros, F, p) %>% 
  unite(temp1, variables, temp) %>% 
  spread(temp1, numeros) %>% 
  mutate(factores = recode(factores, 
                           "disturb_year" = "Drougth event", 
                           "disturb_year:site" = "Drougth event X Site", 
                           "site" = "Site")) %>% 
  arrange(match(factores, c("Drougth event", "Site", "Drougth event X Site")))


colnames(dff) <- c("", "rc\nF", "rc\np", "rrs\nF", "rrs\np", "rs\nF", "rs\np", "rt\nF", "rt\np")
pander(dff,
             round=c(0,2,3,2,3,2,3,2,3),
             digits=c(0,5,4,5,4,5,4,5,4),
             keep.line.breaks = TRUE
             )
dff

```

```{r, echo=FALSE, include = FALSE}
### Table R1_evi sin rrs 
df <- read.csv(here("/out/anovas_resilience/huber_evi", "trimmed_anovas.csv"), header = TRUE)
names(df) <- c('factores', 'F', 'p', 'variables')

dff <- df %>% 
  filter(variables != "rrs") %>% 
  gather(temp, numeros, F, p) %>% 
  unite(temp1, variables, temp) %>% 
  spread(temp1, numeros) %>% 
  mutate(factores = recode(factores, 
                           "disturb_year" = "Drougth event", 
                           "disturb_year:site" = "Drougth event X Site", 
                           "site" = "Site")) %>% 
  arrange(match(factores, c("Drougth event", "Site", "Drougth event X Site")))


# knitr::kable(dff, 
#       col.names = c("", "F", "p", "F", "p", "F", "p", "F", "p"),
#       digits=c(0,2,3,2,3,2,3,2,3))

dff_evi <- dff %>% mutate(target = 'EVI')

colnames(dff) <- c("", "rc\nF", "rc\np", "rs\nF", "rs\np", "rt\nF", "rt\np")
pander(dff,
             round=c(0,2,3,2,3,2,3,2,3),
             digits=c(0,5,4,5,4,5,4,5,4),
             keep.line.breaks = TRUE
             )
dff

```

```{r, echo=FALSE, include = FALSE}

### Table R1_bai
df <- read.csv(here("/out/anovas_resilience/huber_bai", "trimmed_anovas.csv"), header = TRUE)
names(df) <- c('factores', 'F', 'p', 'variables')

dff <- df %>% gather(temp, numeros, F, p) %>% 
  unite(temp1, variables, temp) %>% 
  spread(temp1, numeros) %>% 
  mutate(factores = recode(factores, 
                           "disturb_year" = "Drougth event", 
                           "disturb_year:site" = "Drougth event X Site", 
                           "site" = "Site")) %>% 
  arrange(match(factores, c("Drougth event", "Site", "Drougth event X Site")))


# knitr::kable(dff, 
#       col.names = c("", "F", "p", "F", "p", "F", "p", "F", "p"),
#       digits=c(0,2,3,2,3,2,3,2,3))

colnames(dff) <- c("", "rc\nF", "rc\np", "rrs\nF", "rrs\np", "rs\nF", "rs\np", "rt\nF", "rt\np")
pander(dff,
             round=c(0,2,3,2,3,2,3,2,3),
             digits=c(0,5,4,5,4,5,4,5,4),
             keep.line.breaks = TRUE
             )
dff

```

```{r, echo=FALSE, include = FALSE}
### Table R1_bai sin rrs 
df <- read.csv(here("/out/anovas_resilience/huber_bai", "trimmed_anovas.csv"), header = TRUE)
names(df) <- c('factores', 'F', 'p', 'variables')

dff <- df %>% 
  filter(variables != "rrs") %>% 
  gather(temp, numeros, F, p) %>% 
  unite(temp1, variables, temp) %>% 
  spread(temp1, numeros) %>% 
  mutate(factores = recode(factores, 
                           "disturb_year" = "Drougth event", 
                           "disturb_year:site" = "Drougth event X Site", 
                           "site" = "Site")) %>% 
  arrange(match(factores, c("Drougth event", "Site", "Drougth event X Site")))

dff_bai <- dff %>% mutate(target = 'BAI')

# knitr::kable(dff, 
#       col.names = c("", "F", "p", "F", "p", "F", "p", "F", "p"),
#       digits=c(0,2,3,2,3,2,3,2,3))


colnames(dff) <- c("", "rc\nF", "rc\np", "rs\nF", "rs\np", "rt\nF", "rt\np")
pander(dff,
             round=c(0,2,3,2,3,2,3,2,3),
             digits=c(0,5,4,5,4,5,4,5,4),
             keep.line.breaks = TRUE
             )
dff

```

```{r, echo=FALSE}
# table 2 (r1)
dffs <- dff_bai %>% bind_rows(dff_evi) %>% dplyr::select(8,1:7)

# write.csv(dffs, here("/out/anovas_resilience", "trimmed_anovas_joined.csv"), row.names = FALSE)

# kable(dffs, format = "latex", booktabs = T,
#       col.names = c("", "F", "p", "F", "p", "F", "p", "variable"),
#       digits=c(0,2,3,2,3,2,3,2,3,0)) %>% 
#   kable_styling(font_size = 8) %>% 
#   add_header_above(c("", "rc" = 2, "rs" = 2, "rt" = 2))


dffs <- dffs %>% 
  mutate_at(c(3,5,7), round, 2) %>%
  mutate_at(c(4,6,8), round, 3)

colnames(dffs) <- c("variable", "factores", "rc\nF", "rc\np", "rs\nF", "rs\np", "rt\nF", "rt\np")
pander(dffs)
```

