---
title: "Analysis Stand Features "
author: "AJ Perez-Luque (@ajpelu)"
date: "2017 May"
output:  
  md_document:
    variant: markdown_github
---

```{r, warning=FALSE, message=FALSE}}
library("tidyverse")
library("raster")
library("stringr")
library('rgdal')
library("sp")
library("knitr")
library("broom")
library("multcomp")
library("pander")
library("devtools")
source_gist("https://gist.github.com/ajpelu/194e721077ec045a2b864088908e7aca", filename = 'table_glht.r') # multicomp table
```


# Read and prepare data 
```{r, echo=FALSE}
# machine <- 'ajpelu'
machine <- 'ajpeluLap'
di <- paste0('/Users/', machine, '/Dropbox/phd/phd_repos/qpyr_dendro/', sep='')


# Read tree data
tree <- read.csv(file=paste0(di, '/data_raw/dendro_competence.csv'), header=TRUE, sep=',')



# Read spatial data 
# Centroid of focal tree 
## filename 
mygpx_ca <- paste0(di, 'data_raw/geoinfo/dendro_ca.GPX')
mygpx_sj <- paste0(di, 'data_raw/geoinfo/dendro_sj.GPX')

## reading  
field_work_ca <- readOGR(mygpx_ca, layer="waypoints", verbose = FALSE)
field_work_sj <- readOGR(mygpx_sj, layer="waypoints", verbose = FALSE)
```

* Two datasets: focal tree and competence 
```{r}
# Compute diameter (mm)
tree <- tree %>% 
  mutate(dn_mm = (perim_mm / pi))
         

# Set levels of eleveation 
sj_lowcode  <- paste0('A', str_pad(1:10, 2, pad='0'))
sj_highcode <- paste0('A', 11:20)
ca_lowcode <- c(paste0('B', str_pad(1:10, 2, pad='0')),
            paste0('B', 26:30))
ca_highcode <- paste0('B', 11:25)

tree <- tree %>% 
  mutate(elevF = ifelse(id_focal %in% sj_lowcode, 'Low',
                       ifelse(id_focal %in% sj_highcode, 'High',
                              ifelse(id_focal %in% ca_lowcode, 'Low', 'High')))) %>%
  mutate(site = paste0(loc, '_', elevF))


# Get only focal trees  
ft <- tree %>% 
  filter(sp=='Focal') %>% 
  filter(id_focal!='Fresno') 

# Get only no focal trees 
nft <- tree %>% 
  filter(sp!='Focal') 
```

# General Variables 
```{r}
general_var <- ft %>% group_by(loc, site) %>% count() 

general_var %>% kable
```



# Spatial Info
```{r, spatialData} 
## Get coordinates of spatial data  
sp_ca <- as.data.frame(field_work_ca) %>% 
  dplyr::select(ele, name, lat = coords.x2, long = coords.x1) 

sp_sj <- as.data.frame(field_work_sj) %>% 
  dplyr::select(ele, name, lat = coords.x2, long = coords.x1) 

## Add code site and get centroid (see # http://rspatial.org/analysis/rst/8-pointpat.html)
sp_ca <- sp_ca %>% 
  mutate(loc = 'CA', 
         elevF = ifelse(name %in% ca_lowcode, 'Low', 'High'),
         site = paste0(loc, '_', elevF)) 

coord_ca <- sp_ca %>% 
  group_by(site) %>%
  summarise(lat_m = mean(lat),
            long_m = mean(long))

# plot(sp_ca$long, sp_ca$lat, pch=19, col='gray')
# points(coord_ca$long_m, coord_ca$lat_m, pch=19, col='blue')
  
sp_sj <- sp_sj %>% 
  mutate(loc = 'SJ', 
         elevF = ifelse(name %in% sj_lowcode, 'Low', 'High'),
         site = paste0(loc, '_', elevF))        
coord_sj <- sp_sj %>% 
  group_by(site) %>%
  summarise(lat_m = mean(lat),
            long_m = mean(long))

coords_sites <- coord_sj %>% rbind(coord_ca)

#plot(sp_sj$long, sp_sj$lat, pch=19, col='gray')
#points(coord_sj$long_m, coord_sj$lat_m, pch=19, col='blue')

coords_sites %>% kable()
```

# Topographic data
## Data summary 
```{r}
# Read topo data 
topo <- read.csv(file=paste(di, "/data/topo/topo.csv", sep=""), header=TRUE, sep=',')

topo <- topo %>% 
  mutate(loc = ifelse(str_detect(name, "A"), 'SJ', 'CA'),
         elevF = ifelse(name %in% sj_lowcode, 'Low',
                        ifelse(name %in% sj_highcode, 'High',
                              ifelse(name %in% ca_lowcode, 'Low', 'High')))) %>%
  mutate(site = paste0(loc, '_', elevF)) %>% 
  mutate(site = as.factor(site),
         loc = as.factor(loc),
         elevF = as.factor(elevF))
                      

topo_summary <- topo %>%
  group_by(site) %>%
  summarise(mde_m = mean(mde),
            mde_sd = sd(mde),
            mde_min = min(mde),
            mde_max = max(mde),
            slope_m = mean(slope),
            slope_sd = sd(slope))



# Another way to obtain summary values 
variables <- c('mde','slope','aspect')
auxdf <- data.frame() 

for (i in variables){ 
aux <- topo %>% 
  dplyr::group_by(site) %>% 
  summarise_each_(funs(mean, sd, se=sd(.)/sqrt(n())), i) %>% mutate(variable=i) 

auxdf <- rbind(auxdf, aux) }
```

## ANOVAs 
### Elevation
```{r}
mivariable <- 'mde'

# Model 
myformula <- as.formula(paste0(mivariable, " ~ site"))
mymodel <- aov(myformula, data=topo)

auxdf %>% 
  dplyr::filter(variable==mivariable) %>% 
  pander(round=4, caption=paste0('Mean values (', mivariable,')'))


## Summary model 
tm <- broom::tidy(mymodel)

# See http://my.ilstu.edu/~wjschne/444/ANOVA.html#(1) 
pander(tm, round=5,caption = "ANOVA table", missing = '', 
       emphasize.strong.cells = 
               which(tm < 0.1 & tm == tm$p.value, arr.ind = T))


## Multiple comparison 
tuk <- glht(mymodel, linfct = mcp(site = "Tukey"))

# Convert comparisons into letters 
df_letter <- fortify(cld(tuk)) %>%
  transmute(site = as.factor(lhs),
         tukey = letters) %>%
  mutate(variable = mivariable)

aux_name <- paste0('df_tuk_', mivariable)
assign(aux_name, df_letter)

# Get table 
mymult <- as.data.frame(table_glht(tuk))
pander(mymult, round=4,caption = "Post hoc comparison (Tukey, alpha = 0.05)", missing = '', 
       emphasize.strong.cells = 
               which(mymult < 0.05 & mymult == mymult[,4], arr.ind = T))
```


### Slope
```{r}
mivariable <- 'slope'

# Model 
myformula <- as.formula(paste0(mivariable, " ~ site"))
mymodel <- aov(myformula, data=topo)

auxdf %>% 
  dplyr::filter(variable==mivariable) %>% 
  pander(round=4, caption=paste0('Mean values (', mivariable,')'))


## Summary model 
tm <- broom::tidy(mymodel)

# See http://my.ilstu.edu/~wjschne/444/ANOVA.html#(1) 
pander(tm, round=5,caption = "ANOVA table", missing = '', 
       emphasize.strong.cells = 
               which(tm < 0.1 & tm == tm$p.value, arr.ind = T))


## Multiple comparison 
tuk <- glht(mymodel, linfct = mcp(site = "Tukey"))

# Convert comparisons into letters 
df_letter <- fortify(cld(tuk)) %>%
  transmute(site = as.factor(lhs),
         tukey = letters) %>%
  mutate(variable = mivariable)

aux_name <- paste0('df_tuk_', mivariable)
assign(aux_name, df_letter)

# Get table 
mymult <- as.data.frame(table_glht(tuk))
a <- pander(mymult, round=4,caption = "Post hoc comparison (Tukey, alpha = 0.05)", missing = '', 
       emphasize.strong.cells = 
               which(mymult < 0.05 & mymult == mymult[,4], arr.ind = T))
```



# Competition data
```{r}
# Read competition
compe <- read.csv(file=paste(di, "/data/competence/competence_indices.csv", sep=""), header=TRUE, sep=',')

compe <- compe %>% 
  mutate(name = id_focal) %>% 
  mutate(loc = ifelse(str_detect(name, "A"), 'SJ', 'CA'),
         elevF = ifelse(name %in% sj_lowcode, 'Low',
                        ifelse(name %in% sj_highcode, 'High',
                              ifelse(name %in% ca_lowcode, 'Low', 'High')))) %>%
  mutate(site = paste0(loc, '_', elevF)) %>% 
  mutate(site = as.factor(site),
         loc = as.factor(loc),
         elevF = as.factor(elevF))

```


```{r}
compara <- function(df, mivariable){ 
  require('dplyr')
  require('multcomp')
  require('broom') 
  # mivariable: variabe of interest
  
  output <- list() 
  
  # Model formulation
  myformula <- as.formula(paste0(mivariable, " ~ site"))
  
  # AOV 
  mymodel <- aov(myformula, data=df)
  
  # Summary AOV (broom style)
  tm <- broom::tidy(mymodel)
  
  # Multiple comparison 
  tuk <- glht(mymodel, linfct = mcp(site = "Tukey"))
  
  # Convert comparisons into letters 
  df_letter <- fortify(cld(tuk)) %>% 
    transmute(site = as.factor(lhs),
         tukey = letters) %>%
    mutate(variable = mivariable)
  
  aux_name <- paste0('df_tuk_', mivariable)
  assign(aux_name, df_letter)
  
  mymult <- as.data.frame(table_glht(tuk))
  
  output$mymodel <- mymodel
  output$tm <- tm
  output$aux_name <- df_letter
  output$mymult <- mymult
  
  return(output)
}  
```

```{r}

# Select only variables to compare 
compe_sel <- compe %>% dplyr::select(ba:dnn,site)
# Get vector with variables 
variables <- compe %>% dplyr::select(ba:dnn) %>% names()

for (i in variables){ 
  
  # apply comparison
  out_compara <- compara(df=compe_sel, mivariable = i)
  
  out_name  <- paste0('aov_', i)
  assign(out_name, out_compara)

  }









 


ala <- xxx(df=topo, mivariable='slope')


auxdf %>% 
  dplyr::filter(variable==mivariable) %>% 
  pander(round=4, caption=paste0('Mean values (', mivariable,')'))

# See http://my.ilstu.edu/~wjschne/444/ANOVA.html#(1) 
pander(tm, round=5,caption = "ANOVA table", missing = '', 
       emphasize.strong.cells = 
               which(tm < 0.1 & tm == tm$p.value, arr.ind = T))


## Multiple comparison 
tuk <- glht(mymodel, linfct = mcp(site = "Tukey"))

# Convert comparisons into letters 
df_letter <- fortify(cld(tuk)) %>%
  transmute(site = as.factor(lhs),
         tukey = letters) %>%
  mutate(variable = mivariable)

aux_name <- paste0('df_tuk_', mivariable)
assign(aux_name, df_letter)

# Get table 
mymult <- as.data.frame(table_glht(tuk))



for (i in variables){
  
  mymult <- 
    
  aux <- 
pander(aov_dnn$mymult, round=4,caption = "Post hoc comparison (Tukey, alpha = 0.05)", missing = '', 
     emphasize.strong.cells = 
             which(aov_ba$mymult < 0.05 & aov_ba$mymult == aov_ba$mymult[,4], arr.ind = T))      
              

aov_ba$mymult
  
```             
                
                
                
                
