---
title: "Dendro review"
author: "AJ Perez-Luque (@ajpelu)"
output: 
  md_document:
    variant: markdown_github
bibliography: ../references.bib 
csl: ../ecology.csl
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, warning=FALSE, error=TRUE, message=FALSE)
```


```{r packages, warning=FALSE, message=FALSE, echo=FALSE}
library("here")
library("tidyverse")
library("maps")
library("mapdata")
library("ggmap")
library("ggrepel")
library("cowplot")
library("ggExtra")
```

Dendro review 

```{r}
df <- read.csv(file=here::here("data_raw/dendro_review/dendro_qp_review.csv"), header=TRUE)



spain <- map_data('world', region=c("spain", "portugal"))

s <- ggplot() + 
  geom_polygon(data = spain, aes(x=long, y = lat, group = group),
                            fill=NA, colour="gray") + 
  coord_fixed(1.3) +
  geom_point(data = df, aes(x=long, y=lat, size=length), 
            shape = 21, colour = "black", fill="white", alpha=0.4) +
             #, size=length), alpha=0.3) + 
  # geom_text_repel(data = subset(df, ), aes(x=long, y=lat, label=refs)) + 
  # geom_label(data = df, aes(x=long, y=lat, size=length, label=length)) +
  scale_size(range=c(1,6), breaks=c(0,50,100,200,300,350),
             guide = guide_legend(title="Age (years)")) + 
  xlab('') + ylab('') + theme_void() + 
  theme(legend.position = "top")
  
  
  # theme(panel.grid = element_blank(),
  #       axis.line=element_blank())
```


```{r}
ggplot(df, aes(length)) + geom_density()


dfall <- subset(df, elev > 500)
lm_all <- lm(elev~length, data=dfall)

dfsn <- subset(df, sn == 'yes')
lm_sn <- lm(elev~length, data=dfsn)

# Labels r2 
label_sn <- paste("R[sn]^2 == ", round(summary(lm_sn)$r.squared,4))

label_all <- paste("R[all]^2 == ", round(summary(lm_all)$r.squared,4))

label_both <- paste0('atop(R[all]^2 ==',round(summary(lm_all)$r.squared,4),
            ', R[sn]^2 ==',round(summary(lm_sn)$r.squared,4), ')')
```

```{r}


elev_age <- ggplot(df, aes(x=elev, y=length, colour=sn)) + 
  geom_smooth(data = subset(df, elev > 500), se=FALSE, method = 'lm', colour="black") +
  geom_smooth(data = subset(df, sn == 'yes'),se=FALSE, method = 'lm', colour='grey71') +
  geom_point(size = 3) + theme_bw() + 
  theme(panel.grid = element_blank(), legend.position="none") + 
  geom_text_repel(data = subset(df, !(refs %in% c("SJ","CA-High", "CA-Low"))), 
                  size = 3, aes(label=refs)) +
  geom_label_repel(data = subset(df, refs %in% c("SJ","CA-High", "CA-Low")), 
                   size = 5, aes(label=refs),
                   box.padding = 0.25, point.padding = 0.3) +
  xlab('Elevation (m)') + ylab('Age (years)') +
  scale_colour_manual(values = c("black", "grey71")) + 
  ylim(0,350) 
  


elev_age + annotation_custom(ggplotGrob(s), xmin = 0, xmax = 1400, ymin = 160) +
  annotate("text", label = label_both, x = 150, y = 50, size = 5, parse = TRUE)

```


