---
title: "Summary Dendro"
author: "AJ Perez-Luque (@ajpelu)"
date: "2017 Dec"
output:  
  md_document:
    variant: markdown_github
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8,warning=FALSE, message=FALSE)
```


```{r, warning=FALSE, message=FALSE}
library("tidyverse")
library("stringr")
library("dplR")
library("knitr")
library("pander")
library("here")

```

```{r}
# Compara 
comparaKW <- function(df, mivariable){ 
  require(PMCMR)
  require(multcompView) 
  
  output <- list() 
  
  # Model formulation
  myformula <- as.formula(paste0(mivariable, " ~ site"))
  
  # Kruskal Wallis  
  kt <- kruskal.test(myformula, data = df) 
  
  # Summary AOV (broom style)
  tm <- broom::tidy(kt)
  tm$mi_variable <- mivariable
  
  # Dunn's test 
  object <- posthoc.kruskal.dunn.test(myformula, data=df, p.adjust.method = "bonferroni")
  
  # Get dataframe with letters and pvalues (#from summary.PMCMR)
  pval <- as.numeric(object$p.value)
  stat <- as.numeric(object$statistic)
  grp1 <- as.numeric(c(col(object$p.value)))
  cnam <- colnames(object$p.value)
  grp2 <- as.numeric(c(row(object$p.value)))
  rnam <- rownames(object$p.value)
  H0 <- paste(cnam[grp1], " = ", rnam[grp2])
  OK <- !is.na(pval)
  xdf <- data.frame(H0 = H0[OK], statistic = stat[OK], p.value = format.pval(pval[OK], 5))
  
  # Get letters (using multcompView) See viggnete PMCMR 
  dt_letters  <- multcompView::multcompLetters(get.pvalues(object), threshold = 0.05)
  

  output$KW <- tm
  output$post_hoc <- xdf
  output$letters <- dt_letters
  return(output)
  }

```


# Read y Prepare data 
* Leer datos `rwl` de SJ y CA

```{r, echo=FALSE}
machine <- 'ajpelu'
# machine <- 'ajpeluLap'
di <- paste0('/Users/', machine, '/Dropbox/phd/phd_repos/qpyr_dendro/', sep='')

# sj 
sj <- read.rwl(fname=paste0(di, '/data_raw/dendro_ring/sn_sanjuan/sn_sanjuan.rwl'), format="tucson")

# canar 
ca <- read.rwl(fname=paste0(di, '/data_raw/dendro_ring/sn_canar/sn_canar.rwl'), format="tucson")
```

Computar RWI para tres sitios CA_High, CA_Low, SJ.  

# Preparar datos para computar RWI 
```{r}
source(paste0(di, 'script/R/computeSpline.R'))
source(paste0(di, 'script/R/rw_byTree.R'))
```


```{r}
# Replace SNA by SJ and SNB by CA
names(ca) <- stringr::str_replace(names(ca), "SNB", "CA") 
names(sj) <- stringr::str_replace(names(sj), "SNA", "SJ")

# Remove g in name of some cores of CA. 
names(ca) <- stringr::str_replace(names(ca), "g", "")
```

* Crear dataframes `rwl` por cada sitio CA_High, CA_Low, SJ

```{r}
# Create subset to compare between sites 
caL <- ca[,c("CA0101","CA0102","CA0201","CA0202","CA0301","CA0302","CA0401","CA0402","CA0501","CA0502",
             "CA0601","CA0602","CA0701","CA0702","CA0801","CA0802","CA0901","CA0902","CA1001","CA1002",
             "CA2601","CA2602","CA2701","CA2702","CA2801","CA2802","CA2901","CA2902","CA3001","CA3002")] 
caH <- ca[, c("CA1101","CA1102","CA1201","CA1202","CA1301","CA1302","CA1401","CA1402","CA1501","CA1502",
              "CA1601","CA1602","CA1701","CA1702","CA1801","CA1802","CA1901","CA1902","CA2001","CA2002",
              "CA2101","CA2102","CA2201","CA2202","CA2301","CA2302","CA2401","CA2402","CA2501","CA2502")]

# remove the rows with NA across all columns 
caL <- caL[rowSums(is.na(caL))!=ncol(caL), ]
```


### Summary Dendro 

* Summary stats of RWL 

```{r}
rwl_stat_sj <- rwl.stats(sj)
rwl_stat_caH <- rwl.stats(caH)
rwl_stat_caL <- rwl.stats(caL)

rwl_stat_sites <- rbind(rwl_stat_sj, rwl_stat_caH, rwl_stat_caL) %>% 
  mutate(
  site = as.factor(case_when(
    series %in% names(sj) ~ "sj", 
    series %in% names(caH) ~ "caH", 
    series %in% names(caL) ~ "caL")),
  tree = as.numeric(substr(series, 3, 4)),
  radi = as.numeric(substr(series, 5, 6))
  )

# average age 
age_sites <- rwl_stat_sites %>% 
  group_by(site) %>% 
  dplyr::summarise(age_mean = mean(year, na.rm = TRUE), 
         age_std = sd(year)) %>% as.data.frame()

comparaAges <- comparaKW(rwl_stat_sites, 'year')

letrasAges <- data.frame(site = names(comparaAges$letters$Letters),
                            age_l = comparaAges$letters$Letters) 

age_sites <- age_sites %>% inner_join(letrasAges, by ='site')

pander(age_sites) 
write.csv(age_sites, file=paste(di, "data/dendro_summary/site3_avg_ages.csv", sep=""), row.names = FALSE)


rwl_sites_summ <- rwl_stat_sites %>% 
  group_by(site) %>% 
  dplyr::summarise(n_trees = length(unique(tree)),
                   n_radii =n(), 
                   year_first = min(first), 
                   year_last = max(last), 
                   year_length = max(year),
                   rw_mean = mean(mean, na.rm = TRUE), 
                   rw_std = mean(stdev, na.rm = TRUE),
                   sens1 = mean(sens1, na.rm = TRUE), 
                   sens2 = mean(sens2, na.rm = TRUE), 
                   ar1 = mean(ar1, na.rm = TRUE)) %>% 
  as.data.frame()



pander(rwl_sites_summ)
```

* sample deepth 

```{r}
# sample depth 
sampleDepth <- function(x, site){ 
  x$samps <- rowSums(!is.na(x))
  x$year <- row.names(x)
  x$site <- site
  out <- x[,c("samps", "year", "site")]
  return(out)
} 

d_sj <- sampleDepth(sj, site='sj')
d_caL <- sampleDepth(caL, site='caL')
d_caH <- sampleDepth(caH, site='caH')

d_sites <- rbind(d_sj, d_caH, d_caL)


d <- d_sites %>% 
  filter(samps >= 5) %>% 
  group_by(site) %>% 
  slice(which.min(year)) %>% 
  mutate(
    year = as.numeric(year),
    length_year = (2016 - year + 1)) %>%  
  as.data.frame() 
 
pander(d) 
```


* Combining tables 

```{r}
df <- d %>% 
  dplyr::select(-samps, -year) %>% 
  rename(year_length5 = length_year) %>% 
  left_join(rwl_sites_summ, by='site') %>% 
  dplyr::select(
    site, n_trees, n_radii, 
    first_year = year_first, last_year = year_last, 
    length_year = year_length, length_year5 = year_length5, 
    rw_mean, rw_std, ms2 = sens2, ar1)

pander(df)
```

* Summary stats of Residual chronos

```{r}
rwi_stats <- read.csv(file=paste(di, "data/dendro_summary/site3_dendro_rwi.csv", sep=""),  header=TRUE, sep=',')
```


# Dendro table 
```{r}
dendro_summary <- rwi_stats %>% 
  dplyr::select(rbar.wt, eps, site) %>% 
  inner_join(df, by='site') %>% 
  dplyr::select(site:ar1, rbar.wt, eps)

write.csv(dendro_summary, file=paste(di, "data/dendro_summary/site3_dendro_summary.csv", sep=""), row.names = FALSE)

pander(dendro_summary, caption='Dendrochronological summary by sites') 
```



```{r}

cofecha <- read_delim(here::here("/data_raw/dendro_ring/cofechas.csv"), delim = ";") %>% 
  mutate(site = as.factor(site))

rbt <- cofecha %>% 
  group_by(site) %>% 
  summarise(rbt = mean(corr_w_master))

```



