---
title: "Growing season vs. Drought"
author: "AJ Perez-Luque (@ajpelu)"
date: "2017 Feb"
output:  
  md_document:
    variant: gfm
bibliography: ../refs/references.bib
csl: ../refs/ecology.csl
editor_options: 
  chunk_output_type: console
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8,warning=FALSE, message=FALSE)
```


```{r, warning=FALSE, message=FALSE}
library("tidyverse")
library("here")
library("lubridate")
library("anytime")
library("rdryad")
```

```{r}
# Datos de iv 
iv <- read.csv(here::here("data/evi/iv_composite.csv"), header = TRUE, sep = ',')

evi_profile_dat <- iv %>% 
  group_by(composite) %>% 
  dplyr::summarise(mean=mean(evi, na.rm=T),
            sd = sd(evi, na.rm=T),
            se = sd/sqrt(length(evi))) %>% 
  mutate(composite_dates = 
           plyr::mapvalues(composite,
                           c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23),
                           c('01-01','01-17','02-02','02-18','03-06','03-22','04-07','04-23',
                             '05-09','05-25','06-10','06-26','07-12','07-28','08-13','08-29',
                             '09-14','09-30','10-16','11-01','11-17','12-03','12-19'))) %>%
  mutate(cd = as.Date(composite_dates, format = '%m-%d'))

``` 



```{r}
# datos de Drought
dy <- read.csv(file=here::here('data/sequias', 'severe_spei12.csv'), header=TRUE)

# Convertir en datos de fecha inicio y fecha fin y convertir en falsa fecha

dy <- dy %>% 
  filter(d_duration > 2) %>%  
  separate(rangeDate, c("init", "end"), sep=" - ", remove = FALSE) %>% 
  mutate(miny = ifelse(minyear %in% c(1913,1998), 2018, 2019), 
         maxy = ifelse(maxyear == 1946, 2020, 2019),
         iD = anydate(paste(miny, init, sep="-")),
         eD = anydate(paste(maxy, end, sep="-"))) %>% 
  mutate(r = rank(d_severity, ties.method = "first")) %>% 
  mutate(mean = rescale(r, to =c(0.2, 0.33))) %>% 
  mutate(year = ifelse(minyear == maxyear, minyear, paste(minyear,maxyear, sep="-")))


```

```{r}
micolor <- '#455883'

evi_profile <- ggplot(evi_profile_dat, aes(cd, y=mean)) + 
  geom_errorbar(aes(ymin = mean - 10*se, ymax= mean + 10*se), width=4, colour=micolor, size=.8) + 
  #geom_errorbar(aes(ymin = mean - sd, ymax= mean + sd), width=4, colour='black') +
  geom_line(colour=micolor, size=.8) + 
  geom_point(size=3,colour=micolor) +
  geom_point(size=1.5, colour='white')+
  scale_x_date(labels = function(x) format(x, "%b"),
               breaks = date_breaks('month')) + 
  ylab('EVI') + xlab('Date') + 
  theme_bw() +
  theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank()) +
  theme_classic()
#format(x, "%d-%b") 

combinado <- evi_profile + 
  geom_segment(data = dy, aes(y = mean, x= iD, xend =eD, yend = mean, colour = d_severity), 
               size = 8, alpha = 0.7) +
  geom_text(data = dy, aes(label = year, x = (iD + floor(eD-iD)/2))) +
  scale_colour_gradient(low = "orange", high = "red") + 
  labs(colour = "Drought Severity")
```

```{r}
# PLOT EVI + DROUGHT 
combinado2 <- ggplot(evi_profile_dat, aes(cd, y=mean)) + 
  scale_x_date(labels = function(x) format(x, "%b"), breaks = date_breaks('month')) + 
  theme_bw() +
  theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank()) +
  theme_classic() +
  geom_segment(data = dy, aes(y = mean, x= iD, xend =eD, yend = mean, colour = d_severity), 
               size = 8, alpha = 0.7) +
  geom_text(data = dy, aes(label = year, x = (iD + floor(eD-iD)/2))) +
  scale_colour_gradient(low = "orange", high = "brown") + 
  labs(colour = "Drought Severity") +
  geom_errorbar(aes(ymin = mean - 10*se, ymax= mean + 10*se), width=4, colour=micolor, size=.8) + 
  geom_line(colour=micolor, size=.8) + 
  geom_point(size=3,colour=micolor) +
  geom_point(size=1.5, colour='white') + 
  ylab('EVI') + xlab('Date') 




pdf(here::here('/out/drought_evi', 'evi_droughts.pdf'), width=8, height = 5)
combinado2
dev.off()


# Get data from Dryad 
# Peres de Lis 2016 et al. https://datadryad.org/resource/doi:10.5061/dryad.1cn19
# x <- dryad_files('10.5061/dryad.1cn19')

```
