---
title: "First analysis"
author: "AJ Perez-Luque (@ajpelu)"
date: "2016 Nov"
output:  
  md_document:
    variant: markdown_github
---

```{r packages, warning=FALSE, message=FALSE}}
library("dplyr")
library("ggplot2")
```

# Read data 
```{r wd, echo=FALSE}
# machine <- 'ajpelu'
machine <- 'ajpeluLap'
di <- paste('/Users/', machine, '/Dropbox/phd/phd_repos/qpyr_dendro/', sep='')

# tree data
tree <- read.csv(file=paste0(di, 'data_raw/tree_data.csv'), header=TRUE, sep=',')

# gps data 
elev <- read.csv(file=paste0(di, "/data/elev.csv"), header=TRUE, sep = ',')
```

# Prepare data
```{r}
qpyr <- tree %>% 
  inner_join(elev, by='name') %>% 
  filter(name != 'Fresno') 


low_ca<- c('B01', 'B02', 'B03', 'B04', 'B05', 'B06', 'B07', 'B08', 'B09', 'B10',
         'B26', 'B27', 'B28', 'B29', 'B30')
low_sj <- c('A01', 'A02', 'A03', 'A04', 'A05', 'A06', 'A07', 'A08', 'A09', 'A10')
# high_sj<- c('A11', 'A12', 'A13', 'A14', 'A15', 'A16', 'A17', 'A18', 'A19', 'A20')
# high_ca <- c('B11', 'B12', 'B13', 'B14', 'B15', 'B16', 'B17', 'B18', 'B19', 'B20', 
#           'B21', 'B22', 'B23', 'B24', 'B25')  

qpyr <- qpyr %>% 
  mutate(stand = ifelse(loc == 'SJ',
       ifelse(name %in% low_sj, 'low', 'high'), 
       ifelse(name %in% low_ca, 'low', 'high')))

qpyr %>% 
  ggplot(aes(y=height, x=perimeter)) + 
  geom_point(size=2) + geom_smooth(method = "lm", se=FALSE) +
  facet_grid(loc~stand) + theme_bw()
    

# TODO: Tape sensu Korner --> how many wood does tree invert into growht in height by basimetric area?? LINK to BAI (explore the same pattern with BAI) 
qpyr <- qpyr %>% 
  mutate(diam = 2*pi*(sqrt(perimeter/pi)),
         taper = diam / height)



qpyr %>% 
  ggplot(aes(y=taper, x=elev)) + 
  geom_point(size=2) + facet_wrap(~loc) + geom_smooth(method = "lm", se=FALSE) 

+
  facet_grid(loc~stand) + theme_bw()


   

    

```

