---
title: "Get topographic info of gps points"
author: "AJ Perez-Luque (@ajpelu)"
date: "2016 Nov"
output:  
  md_document:
    variant: markdown_github
---

```{r packages, warning=FALSE, message=FALSE}}
library("rgdal")
library("sp")
library("raster")
library("dplyr")
library("maptools")
```


# Read data 
```{r wd, echo=FALSE}
machine <- 'ajpelu'
# machine <- 'ajpeluLap'
di <- paste('/Users/', machine, '/Dropbox/phd/phd_repos/qpyr_dendro/', sep='')


# Connect with NAS and copy the mde file located at 
# '/cartografia/Informacion_Ambiental/BASES_DE_REFERENCIA_TERRITORIAL/MDE_SN_AreaInfluecia_10m/mde_sn_area_influencia.asc' 
#---------------------------------
```


# Extract data
```{r} 
ditemp <- paste('/Users/', machine, '/Documents/', sep='')
setwd(ditemp)

# read DEM 
# demsn <- raster("mde_sn_area_influencia.asc")
# dme5t ign 
dem1027 <- raster("1027.asc")
dem1042 <- raster("1042.asc")

setwd(di)

## Projection 
# Set projection(demsn)
crs(demsn) <- "+init=epsg:23030"


# Read points data 
gps_point_ca <- readOGR(paste0(di, 'data_raw/geoinfo/dendro_ca.GPX'), layer='waypoints', verbose = FALSE) 
gps_point_sj <- readOGR(paste0(di, 'data_raw/geoinfo/dendro_sj.GPX'), layer='waypoints', verbose = FALSE) 

# Join point 
gps_point <- spRbind(gps_point_ca,gps_point_sj)

# Get elev 
gps_elev <- extract(demsn, gps_point, method='simple', sp=TRUE)

elev <- gps_elev@data %>%
  dplyr::select(ele, name, elev_mde = mde_sn_area_influencia)

# Export data
write.csv(elev, file=paste(di, "/data/elev.csv", sep=""), row.names = FALSE)
```
