---
title: "EOBS Climate data"
author: "AJ Perez-Luque (@ajpelu)"
date: "2017 Dec"
output:
  md_document:
    variant: markdown_github
bibliography: ../references.bib 
csl: ../ecology.csl
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, warning=FALSE, error=TRUE, message=FALSE)
```


```{r packages, warning=FALSE, message=FALSE, echo=FALSE}
library("tidyverse")
library("treeclim")
```

# Cargar los datos
```{r}
machine <- 'ajpelu'
# machine <- 'ajpeluLap'
di <- paste0('/Users/', machine, '/Dropbox/phd/phd_repos/qpyr_dendro/', sep = '')
```

```{r}
eobs <- read.csv(file=paste0(di, 'data_raw/eobs/eobs_data_robles.csv'), header=TRUE, sep=',')
cro <- read.csv(file=paste(di, "data/cronos_medias/cronos_sites_rwi.csv", sep=""), header=TRUE, sep=',')


croN <- cro %>% filter(site == 'sj') %>% dplyr::select(-site) %>% 
  filter(year > 1949)
rownames(croN) <- croN$year 

eobs <- eobs %>% 
  mutate(date = as.Date(str_sub(startDate, 1, 11), format="%Y-%m-%d"), 
         year = lubridate::year(date), 
         month = lubridate::month(date))


cl <- eobs %>% 
  filter(loc == 'N') %>% 
  filter(variable %in% c('rr', 'tg')) %>% 
  dplyr::select(value, variable, year, month) %>% 
  spread(variable, value)

cl <- cl %>% rename(prec = rr, temp = tg) %>% 
  filter(year < 2017)


test <- dcc(chrono = croN, climate = cl)

croN 
# http://czang.org/treeclim.html




eobs %>% filter(variable == 'rr') %>% ggplot(aes(x=date, y=value, colour=loc)) + geom_line() 


```