---
title: "tabla_mean_values Mhuber"
author: "AJ Perez-Luque (@ajpelu)"
date: "2017"
output: pdf_document
bibliography: ../references.bib 
csl: ../ecology.csl
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8,warning=FALSE, error=TRUE, message=FALSE)
```

```{r, warning=FALSE, message=FALSE}
library("tidyverse")
library("pander")
```


```{r, echo=FALSE}
machine <- 'ajpelu'
# machine <- 'ajpeluLap'
di <- paste0('/Users/', machine, '/Dropbox/phd/phd_repos/qpyr_dendro/', sep='')
```


# Read data from EVI 

```{r}
# Estos datos vienen del repo de modis_resilience (/analysis/explore_Resilience.Rmd)
mhuber_evi <- read.csv(file=paste0(di, '/out/anovas_resilience/huber_evi/robust_mhuber.csv'), header = TRUE, sep=",")
mhuber_eviA <- read.csv(file=paste0(di, '/out/anovas_resilience/huber_evi/robust_mhuber_a.csv'), header = TRUE, sep=",")
mhuber_eviB <- read.csv(file=paste0(di, '/out/anovas_resilience/huber_evi/robust_mhuber_b.csv'), header = TRUE, sep=",")
```


```{r}
# Estos datos vienen del repo de modis_resilience (/analysis/explore_Resilience.Rmd)
mhuber_bai <- read.csv(file=paste0(di, '/out/anovas_resilience/robust_mhuber.csv'), header = TRUE, sep=",")
mhuber_baiA <- read.csv(file=paste0(di, '/out/anovas_resilience/robust_mhuber_a.csv'), header = TRUE, sep=",")
mhuber_baiB <- read.csv(file=paste0(di, '/out/anovas_resilience/robust_mhuber_b.csv'), header = TRUE, sep=",")
```


## Tablas Disturb year  
```{r, echo=FALSE}
evi_a <- mhuber_eviA %>% 
  mutate(M.Huber = round(M.Huber, 4),
         lower.ci = round(lower.ci, 4),
         upper.ci = round(upper.ci, 4)) %>% 
  unite("ci", c("lower.ci", "upper.ci"), sep=", ") %>% 
  mutate(ci = paste0('(', ci, ')')) %>% 
  unite("value_EVI", c("M.Huber", "ci"), sep= " ") %>%
  dplyr::select(-MonoLetter, -n) %>% 
  dplyr::select(var, disturb_year, value_EVI, letter_EVI=Letter) %>% as.data.frame() 

evi_a %>% pander() 

bai_a <- mhuber_baiA %>% 
  mutate(M.Huber = round(M.Huber, 4),
         lower.ci = round(lower.ci, 4),
         upper.ci = round(upper.ci, 4)) %>% 
  unite("ci", c("lower.ci", "upper.ci"), sep=", ") %>% 
  mutate(ci = paste0('(', ci, ')')) %>% 
  unite("value_BAI", c("M.Huber", "ci"), sep= " ") %>%
  dplyr::select(-MonoLetter, -n) %>% 
  dplyr::select(var, disturb_year, value_BAI, letter_BAI=Letter) %>% as.data.frame() 

bai_a %>% pander() 

mhuberA <- evi_a %>% inner_join(bai_a, by=c("var", "disturb_year"))

mhuberA %>% pander() 
```


## Tablas site
```{r, echo=FALSE}
evi_b <- mhuber_eviB %>% 
  mutate(M.Huber = round(M.Huber, 4),
         lower.ci = round(lower.ci, 4),
         upper.ci = round(upper.ci, 4)) %>% 
  unite("ci", c("lower.ci", "upper.ci"), sep=", ") %>% 
  mutate(ci = paste0('(', ci, ')')) %>% 
  unite("value_EVI", c("M.Huber", "ci"), sep= " ") %>%
  dplyr::select(-MonoLetter, -n) %>% 
  dplyr::select(var, site, value_EVI, letter_EVI=Letter) %>% as.data.frame() 

evi_b %>% pander() 

bai_b <- mhuber_baiB %>% 
  mutate(M.Huber = round(M.Huber, 4),
         lower.ci = round(lower.ci, 4),
         upper.ci = round(upper.ci, 4)) %>% 
  unite("ci", c("lower.ci", "upper.ci"), sep=", ") %>% 
  mutate(ci = paste0('(', ci, ')')) %>% 
  unite("value_BAI", c("M.Huber", "ci"), sep= " ") %>%
  dplyr::select(-MonoLetter, -n) %>% 
  dplyr::select(var, site, value_BAI, letter_BAI=Letter) %>% as.data.frame() 

bai_b %>% pander() 

```

## Tablas Interaction
```{r, echo=FALSE}
evi <- mhuber_evi %>% 
  mutate(M.Huber = round(M.Huber, 4),
         lower.ci = round(lower.ci, 4),
         upper.ci = round(upper.ci, 4)) %>% 
  unite("ci", c("lower.ci", "upper.ci"), sep=", ") %>% 
  mutate(ci = paste0('(', ci, ')')) %>% 
  unite("value_EVI", c("M.Huber", "ci"), sep= " ") %>%
  dplyr::select(-MonoLetter, -n) %>% 
  dplyr::select(var,  disturb_year, site, value_EVI, letter_EVI=Letter) %>% as.data.frame() 

evi %>% pander() 

bai <- mhuber_bai %>% 
  mutate(M.Huber = round(M.Huber, 4),
         lower.ci = round(lower.ci, 4),
         upper.ci = round(upper.ci, 4)) %>% 
  unite("ci", c("lower.ci", "upper.ci"), sep=", ") %>% 
  mutate(ci = paste0('(', ci, ')')) %>% 
  unite("value_BAI", c("M.Huber", "ci"), sep= " ") %>%
  dplyr::select(-MonoLetter, -n) %>% 
  dplyr::select(var, disturb_year, site, value_BAI, letter_BAI=Letter) %>% as.data.frame() 

bai %>% pander() 
```
